### ISSUE TITLE
while building metadata for contract-transfer - no matching package named `contract_transfer` found

### ISSUE THREAD

**Issue by yangwao** [paritytech/cargo-contract#106]
I think manifest is generated wrong? Should be there a **contract_transfer.wasm**?

![image](https://user-images.githubusercontent.com/5887929/99080000-f805a480-25c0-11eb-8833-0d4e06981e56.png)

**Comment by cmichi** [comment]
@yangwao Thanks for creating an issue for this! There was a typo in the `Cargo.toml` of that example, we just merged a fix into the ink! repository. Can you update your `contract-transfer` example with the latest `Cargo.toml` from https://github.com/paritytech/ink/tree/master/examples/contract-transfer?

**Comment by ascjones** [comment]
Looking again at this though, I believe that since `contract-transfer` with a hyphen is a valid package name. It should handle this.
