### ISSUE TITLE
Add `cargo contract build --verifiable`

### ISSUE THREAD

**Issue by cmichi** [paritytech/cargo-contract#1065]
This is a cross-cutting issue. We need to get a grip on verifiable builds once and forever. 

The core issue is that the Rust compiler doesn't give us a deterministic build of a contract. We looked into this in the past and it's just not possible currently. The only way to have proper verifiable contracts on-chain is:

* The deployed contract has been built in a specified environment.
* The verifier rebuilds the contract in this specified environment.

We have the unfortunate situation now that some block explorers have defined their own specified environment. Meaning they require contracts to be build in this specified environment to be verifiable. This is not ideal. Users have to know about this before they deploy and it applies only to that Explorer then. We want to have one common denominator for everyone out there who wants to verify a contract.

Here's the outline of how we'll get there:

- [x] We add a flag `cargo contract build --verifiable`.
- [x] When invoked we spawn a pre-defined ink! Docker image, build the contract in there and write the Dockerhub id into the metadata. 
- [x] The `Dockerfile` should be part of the `cargo-contract` repository and published to Dockerhub.
- [x] The Docker image should contain ink!, Solang and ask! dependencies, so that in principle contracts from those languages can be build in verifiable mode.
- [x] This will create new optional dependencies for `cargo-contract`: Rust docker bindings and docker.
- [x] Create follow-up issue: Have `cargo-contract` warn if `cargo contract deploy` is invoked against a production chain. Likely by having a hard-coded list for the moment.
- [x] Create follow-up issue: Have Contracts UI warn if users want to deploy unverified contracts to a production chain.

**Comment by SkymanOne** [comment]
For the second point, do you mean the image name? Docket Hub ID is basically a username, and I don't see the point of keeping that information in metadata.

**Comment by SkymanOne** [comment]
Closing as completed
