### ISSUE TITLE
Experiment with some wasm-opt options

### ISSUE THREAD

**Issue by Robbepop** [paritytech/cargo-contract#110]
We currently are not using `wasm-opt`'s `--strip-debug --vacuum --dce` options. They might be useful to us to reduce the resulting `.wasm` files. Experimentation needed.

**Comment by cmichi** [comment]
In that regard experimenting with [these](https://github.com/paritytech/cargo-contract/blob/master/src/cmd/build.rs#L187-L190) binaryen options could also have some benefits:

Currently:
```
    let codegen_config = binaryen::CodegenConfig {
        // execute -O3 optimization passes (spends potentially a lot of time optimizing)
        optimization_level: 3,
        // the default
        shrink_level: 1,
        // the default
        debug_info: false,
    };
```

**Comment by HCastano** [comment]
I've been playing around a bit with some of the optimizations options using some (but not
all) of our example contracts.

For reference, the original sizes with `ink!` on [`hc-bump-allocator`](https://github.com/paritytech/ink/tree/8e84f341960c43676ad0fc22df554b5f49b80d0e) and `cargo-contract` on [`master`](https://github.com/paritytech/cargo-contract/tree/d79d07baae4ea5b84c3bde12cb697ed58a2613d1)
are in the table below.

| Contract | Original | Optimized |
--- | --- | --- |
| erc20          | 51.8K | 30.5K |
| trait-erc20    | 52.3K | 31.0K |
| erc1155        | 65.2K | 45.3K |
| erc721         | 68.3K | 41.1K |
| dns            | 44.2K | 25.3K |
| multisig_plain | 86.2K | 53.6K |


1. Setting `cargo-contract` to `--optimization-passes s`
This saves us ~0.2-0.3K.

2. Setting `cargo-contract` to `--optimization-passes z`
Same as (1).

3. Adding `--vaccum` option to `wasm-opt`
This increases the size by ~0.2-0.3K.

4. Adding `--strip-debug` option to `wasm-opt`
Same as (3).

5. Adding `--dae-optimizing` option to `wasm-opt`
Same as (3).

I think right now changing the opt level default from `-O3` to at least `-Os` is the most
sensible thing to do.

**Comment by athei** [comment]
There are **a lot** of optimization options. I have no idea which are on by default and which are not. Would be nice to find that out. I guess the source code should reveal this information.

For example, `--strip-debug` is on by default. To keep the debug symbols `-g` is needed.

**Comment by cmichi** [comment]
If nobody speaks up in the next days I'll close this issue. We've already set
```
-Oz  execute default optimization passes, super-focusing on code size
```
as a consequence of this issue and it lead to some savings.

We've done some experimenting of individual flags which seemed reasonable, but no further big finding was found. There are a lot more options we could try:
```
$ wasm-opt --help | grep "\-\-" | wc -l
167
```
But it seems that the potential of finding another big thing is low, whereas we have a number of ideas in https://github.com/paritytech/substrate/issues/9354 now, which will definitely lead to significant size improvements. So I think it's reasonable to rather focus our effort there.
