### ISSUE TITLE
binaryen dependency feature

### ISSUE THREAD

**Issue by ascjones** [paritytech/cargo-contract#113]
In https://github.com/paritytech/cargo-contract/pull/95 we add the `binaryen` as a dependency, rather than requiring manual installation. However this 

- Increases the build time which we want to keep as fast and easy as possible. (*edit*: it might not be by much? need to confirm with fresh build)
- Takes up quite a lot of disk space 
- Requires the prerequisities to be installed. 

We could still provide this but behind a feature, and default to using an installed binary, and perhaps we could provide better information to be able to download a prebuilt binary e.g. there is one here https://packages.debian.org/buster/binaryen.

Potentially we could detect the presence of the binary on the `PATH`, and then choose whether to enable this feature but it would require some trickery in `build.rs` so not sure about that.

/cc @Robbepop

**Comment by Robbepop** [comment]
> Potentially we could detect the presence of the binary on the PATH, and then choose whether to enable this feature but it would require some trickery in build.rs so not sure about that.

We do want exactly this. User should not need to specify some crate features to make this happen manually.
