### ISSUE TITLE
Warnings when using `#[no_main]`

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/cargo-contract#1130]
When I ran `cargo contract build --manifest-path /app/dapps/ink-rust/wasm-flipper/contract/flipper/Cargo.toml` to build that Flipper smart contract here https://github.com/ltfschoen/InkTest/blob/main/dapps/ink-rust/wasm-flipper/contract/flipper/lib.rs#L1, it gave error 
```
   Compiling flipper v0.1.0 (/tmp/cargo-contract_2GXX87/dapps/ink-rust/wasm-flipper/contract/flipper)

Exited with error: [E0601]
Your contract must be annotated with the `no_main` attribute.

Examples how to do this:
   - `#![cfg_attr(not(feature = "std"), no_std, no_main)]`
   - `#[no_main]`

ERROR: missing `no_main` attribute
```

So I followed its example of how to do it by changing lib.rs to this:
```rust
#![cfg_attr(not(feature = "std"), no_std, no_main)]
#[no_main]

#[ink::contract]
mod flipper {
...
```

But then when i tried rebuilding it again the same way it gave error:
```bash
   Compiling flipper v0.1.0 (/tmp/cargo-contract_beJ03I/dapps/ink-rust/wasm-flipper/contract/flipper)
warning: crate-level attribute should be an inner attribute: add an exclamation mark: `#![foo]`
 --> /app/dapps/ink-rust/wasm-flipper/contract/flipper/lib.rs:2:1
  |
2 | #[no_main]
  | ^^^^^^^^^^
  |
  = note: `#[warn(unused_attributes)]` on by default
```

But if I change it to 
```rust
#![cfg_attr(not(feature = "std"), no_std, no_main)]
#![no_main]
```
it outputs
```
warning: unused attribute
 --> /app/dapps/ink-rust/wasm-flipper/contract/flipper/lib.rs:2:1
  |
2 | #![no_main]
  | ^^^^^^^^^^^ help: remove this attribute
  |
note: attribute also specified here
 --> /app/dapps/ink-rust/wasm-flipper/contract/flipper/lib.rs:1:43
  |
1 | #![cfg_attr(not(feature = "std"), no_std, no_main)]
  |                                           ^^^^^^^
  = note: `#[warn(unused_attributes)]` on by default
```

But if I change it to just:
```rust
#![cfg_attr(not(feature = "std"), no_std)]
#![no_main]
```
then it doesn't output any warnings at all but compiles successfully too.

But when i look at the simplest ink! example docs https://use.ink/examples/smart-contracts with code here https://github.com/paritytech/ink-examples/blob/main/flipper/lib.rs, it just has 
```
#![cfg_attr(not(feature = "std"), no_std, no_main)]
```
Is this the correct way to do it? Or are there multiple appropriate ways

**Comment by ascjones** [comment]
```
Examples how to do this:
   - `#![cfg_attr(not(feature = "std"), no_std, no_main)]`
   - `#[no_main]`
```
These are two separate ways, arguably you would usually use the feature gated one (the first one).

> Is this the correct way to do it? Or are there multiple appropriate ways

Yes I would recommend the first one `#![cfg_attr(not(feature = "std"), no_std, no_main)]`
