### ISSUE TITLE
Failed to build some contracts with rustc 1.70

### ISSUE THREAD

**Issue by kvinwang** [paritytech/cargo-contract#1139]
```
 [2/4] Post processing code
ERROR: Loading of original wasm failed

Caused by:
    0: Loading of wasm module at '[...]/target/ink/wasm32-unknown-unknown/release/system.wasm' failed
    1: Unknown opcode 192
```
The failed contract is here: https://github.com/Phala-Network/phala-blockchain/tree/master/crates/pink-drivers/system

**Comment by kvinwang** [comment]
There is an upstream discussion: https://github.com/rust-lang/rust/issues/109807

**Comment by ascjones** [comment]
@kvinwang thanks for reporting this we will look into it. Regarding the linked issue,`cargo-contract` does [not explicitly pass](https://github.com/paritytech/cargo-contract/blob/b5db47922f1e898a043d7fbbb0303690f82146a9/crates/build/src/args.rs#L196) `target-feature=-sign-ext`, so is the issue linked relevant? I'm not an expert in these Wasm features so not sure why this opcode would have shown up now when building in `1.70`.

**Comment by kvinwang** [comment]
> so is the issue linked relevant (although I haven't read it properly all the way through)?

Yep, it is relevant. I can also reproduce [the example](https://github.com/rust-lang/rust/issues/109807#issuecomment-1574822323) in that issue with:

 `RUSTFLAGS="-C linker-plugin-lto -C target-cpu=mvp" cargo build --target wasm32-unknown-unknown --release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --no-default-features`

 where `-C linker-plugin-lto` is used by `cargo-contract`.

**Comment by webmaster128** [comment]
> Even if we [update `parity-wasm` ](https://github.com/paritytech/cargo-contract/issues/1141) to support that opcode (it is deprecated...)

A patch for parity-wasm would be much appreciated ❤️ (I know it's deprecated but still)

**Comment by ascjones** [comment]
@webmaster128 the idea is to replace it see https://github.com/paritytech/cargo-contract/issues/1141

**Comment by webmaster128** [comment]
Thank you @ascjones. I'll follow that ticket. We use parity-wasm as well in CosmWasm and getting a patch there short term while looking for alternatives mid-term would be great. But I also understand if there is nobody maintaining parity-wasm anymore.

**Comment by ascjones** [comment]
> We use parity-wasm as well in CosmWasm and getting a patch there short term while looking for alternatives mid-term would be great. But I also understand if there is nobody maintaining parity-wasm anymore.

When we do this I will look at what the filecoin guys have done in https://github.com/filecoin-project/fvm-wasm-instrument, which is a fork of https://github.com/paritytech/wasm-instrument with `parity-wasm` replaced by `was-encoder` and `wasmparser`. Hope that helps!

**Comment by webmaster128** [comment]
FYI you can tell parity-wasm to allow the sign extension opcodes via an already existing feature. This might help short term. See https://github.com/CosmWasm/cosmwasm/pull/1743.

**Comment by ascjones** [comment]
> Turns out you can tell parity-wasm to allow the sign extension opcodes via an already existing feature. This might help short term until the mogration to a different parser is completed. See [CosmWasm/cosmwasm#1743](https://github.com/CosmWasm/cosmwasm/pull/1743).

Fantastic, that is really useful thanks! It will make fixing it on the `cargo-contract` side much easier.

**Comment by webmaster128** [comment]
Not sure if this helps in your case, but we realized that a different way to mitigate the problem is running the compiled Wasm through wasm-opt with [`--signext-lowering`](https://github.com/WebAssembly/binaryen/pull/5676). This ensures none of the operations in question are left, no matter which Rust version you use for compilation. This way you solve the issue for hosts that only support Wasm MVP.

**Comment by hieptran1812** [comment]
@kvinwang Have you fixed this issue? I have this issue as well

**Comment by kvinwang** [comment]
> @kvinwang Have you fixed this issue? I have this issue as well

I use rustc-1.69 as a workaround.
