### ISSUE TITLE
Replace `parity-wasm` usage for post processing

### ISSUE THREAD

**Issue by ascjones** [paritytech/cargo-contract#1141]
`parity-wasm` has been [deprecated](https://github.com/paritytech/parity-wasm/pull/334) for a while, we should migrate to something else. Possibly [wasmparser](https://crates.io/crates/wasmparser) and [wasm-encoder](https://crates.io/crates/wasm-encoder) as suggested [here](https://github.com/filecoin-project/ref-fvm/issues/829).

Rel https://github.com/paritytech/cargo-contract/issues/1139

**Comment by cmichi** [comment]
The PR https://github.com/filecoin-project/fvm-wasm-instrument/pull/6 contains the same migration, we can likely take inspiration from there.
