### ISSUE TITLE
Before contract upload/instantiate: verify that node types match contract types

### ISSUE THREAD

**Issue by cmichi** [paritytech/cargo-contract#1167]
With https://github.com/paritytech/ink/issues/1695 the environmental types of a contract are now persisted to its metadata. Before a contract is uploaded/instantiated to a chain we should conduct a verification that the contract's types actually match the ones from the node metadata.

**Comment by SkymanOne** [comment]
The Substrate Node's does not expose those type in plain. We need first to figure out how to expose those types in the generated metadata using `subxt`
