### ISSUE TITLE
Support multiple `pallet-contracts` versions to interact with

### ISSUE THREAD

**Issue by cmichi** [paritytech/cargo-contract#1168]
`cargo-contract` currently contains a fixture of the node's metadata ([the file is here](https://github.com/paritytech/cargo-contract/blob/master/crates/cargo-contract/src/cmd/runtime_api/contracts_runtime.scale)). This metadata file includes the `pallet-contracts` metadata. If users try to interact with a node that has a different metadata version from the one in their local `cargo-contract` installation, this error will be thrown:

```
ERROR: Metadata: Pallet Contracts Call Contracts has incompatible metadata
```

So currently `cargo-contract` can only target one version of `pallet-contracts` and we should fix this.

We reference the fixture here:
https://github.com/paritytech/cargo-contract/blob/d9950ca212a22d491fb61a022f550361280bbc79/crates/cargo-contract/src/cmd/runtime_api/mod.rs#L20

`subxt` by now supports downloading the node metadata automatically. The API is `#[subxt::subxt(runtime_metadata_url = "wss://rpc.polkadot.io:443")]`. But we don't know the endpoint at compile time, since the user can supply a custom `--url`. 

## The Solution

Modify the `subxt` setup to use dynamic values instead. This same issue has actually already been solved for the ink! end-to-end testing framework, [here is the commit](https://github.com/paritytech/ink/pull/1526/commits/2648f6acd9517a88a6ad7e8d0d45ffd6d3da90af). It should be possible to take that commit as a template and transfer the solution to `cargo-contract`.

**Comment by ascjones** [comment]
Copying my response from https://github.com/paritytech/cargo-contract/pull/1186#issuecomment-1613340426 regarding using different environment types for `AccountId`:

====

Until now we have only targeted a single node configuration, the recent `substrate-contracts-node`, so both the `Environment` types (`AccountId`, `Balance` etc.) are fixed and the generated types and call API (from `subxt` metadata) are fixed against this target node.

What we want is to be able to target different node configurations. I see a couple of different approaches:

1. Make the `Environment` types generic everywhere they are used, maintain multiple versions of the `subxt` metadata for each type of node. At runtime detect which type of node we are targeting and invoke the command with the concrete `Environment` types configuration
  1a. Alternatively replace the subxt metadata with handcrafted calls with generic parameters for `Environment` types
2. Introduce a plugin model whereby we can support any number of configurations/versions of chains, you just need to install a plugin which conforms to the given API for the supported commands.

**Comment by smiasojed** [comment]
The implementation will be split into following parts:
1. Add generics to the extrinsics crate.
2. Create static configurations to communicate with different nodes.
3. Separate the configuration-dependent code into plugins:
a) Design an interface for plugins (plugin could be dynamic library or wasm).
b) Implement the interfaces for plugins.
c) Implement two plugins to prove that it works.

**Comment by smiasojed** [comment]
Point 1 and 2 have been successfully implemented. Moving forward to point 3, our strategy revolves around compiling chain-specific code into WebAssembly (Wasm). This approach ensures seamless communication, even from JavaScript to any substrate based node.

Here's how it could be achieved:

Wrap the Extrinsics Crate:
We'll create a wrapper around the extrinsics crate, abstracting away the usage of generics. Although the extrinsics crate internally relies on generics, our wrapper will handle the correct configuration to parse arguments into the required generics.

Compile to WebAssembly:
Once we have our extrinsics crate wrapper, we'll compile it to WebAssembly using wasm-pack. This allows us to expose its API, which can then be invoked from cargo-contract.

Loading WebAssembly Modules as Plugins:
During runtime, the WebAssembly code will be dynamically loaded as a plugin when the cargo-contract command is executed, facilitating seamless integration and extensibility.

**Comment by smiasojed** [comment]
I think we can close it, as the functionality mentioned in the comment above will not be implemented now.
@cmichi @ascjones what do you think?

**Comment by ascjones** [comment]
Yes I think it is okay to close this. If there is something more required we can open a new issue and link back to this one.
