### ISSUE TITLE
Improved Integration Flexibility for the Extrinsics Crate

### ISSUE THREAD

**Issue by tareknaser** [paritytech/cargo-contract#1195]
# Description:
The current implementation of the `extrinsics` crate's commands presents limitations when integrating them into other projects. These commands are primarily designed to work with `ink!` contracts and lack the necessary flexibility to accommodate customization and usage in other projects. For example: 
 - The existing commands heavily rely on reading information from the `Cargo.toml` file to retrieve details about `ink!` contracts. This tight coupling makes it challenging to use the commands in projects that rely on alternative configuration mechanisms.
 - The command structs within the `extrinsics` crate have private fields and no constructors, making it impossible to initialize them directly from external code. 

# Proposed solutions
1- Public Fields: To enable easy customization, we can make the fields of the command structs public including `ExtrinsicOpts`.
2- Constructor Methods: Implementing constructors for the command structs would provide a convenient initialization method.
3- Moving the commands' logic from the structs into separate functions.

**Comment by xermicus** [comment]
I think that adding builders to [these](https://github.com/paritytech/cargo-contract/blob/master/crates/extrinsics/src/call.rs#L61) might require minimal to no changes to cargo-contract itself, while allowing other consumers to have another interface than just parsing via clap.

**Comment by ascjones** [comment]
I'm curious to understand the use case for this so I can properly think about how the API should be constructed.

**Comment by xermicus** [comment]
Addressed by #1213
