### ISSUE TITLE
docs: cargo contract build --verifiable is not an option

### ISSUE THREAD

**Issue by gaboesquivel** [paritytech/cargo-contract#1223]
**Describe the bug**
`cargo contract build --verifiable` is not an option in 3.0.1

**To Reproduce**
1. install cargo-contract ( cargo-contract-contract 3.0.1-unknown-x86_64-apple-darwin (
2. follow verifiable builds section in readme https://github.com/paritytech/cargo-contract/#verifiable-builds

**Expected behavior**
`cargo contract build --verifiable` successful execution

**Environment (please complete the following information):**
 - OS: [e.g. MacOS Intel i7 Ventura 13.4]
 - `cargo-contract` version 3.0.1

**Comment by ascjones** [comment]
We haven't done a release yet which includes this feature. While you wait for a release you can install with `cargo contract install --git https://github.com/paritytech/cargo-contract --force` then you can use all the latest features including this.
