### ISSUE TITLE
cargo contract build --verifiable not working

### ISSUE THREAD

**Issue by abhijeetbhagat** [paritytech/cargo-contract#1250]
getting an error on my m1 mac:
```
⟩ cargo contract build --verifiable
 [1/3] Image does not exist. Pulling one from the registry
ERROR: Docker responded with status code 404: manifest for paritytech/contracts-verifiable:4.0.0-alpha not found: manifest unknown: manifest unknown
```

1.  `rustup update`
2.  `cargo install --git https://github.com/paritytech/cargo-contract --force`
3.  `cargo contract new testcontract`
4.  `cargo contract build --verifiable`

**Expected behavior**
a verifiable build should be produced

**Environment (please complete the following information):**
 - OS: macos m1
 - rustc version: ﻿﻿rustc 1.73.0-nightly (32303b219 2023-07-29)
 - `cargo-contract` version: cargo-contract-contract 4.0.0-alpha-51e17d7-aarch64-apple-darwin
 - ink! version: 4.2.0

**Comment by sleepyyj** [comment]
@ascjones Missing tag for 4.0.0-alpha.
https://hub.docker.com/r/paritytech/contracts-verifiable/tags

**Comment by SkymanOne** [comment]
> @ascjones Missing tag for 4.0.0-alpha.
> https://hub.docker.com/r/paritytech/contracts-verifiable/tags

Yes. This is a known issue. A new image tag will be pushed this night.

**Comment by SkymanOne** [comment]
The image is live under `latest` and `4.0.0-alpha` tags
