### ISSUE TITLE
Calls to productions chains result in error

### ISSUE THREAD

**Issue by SkymanOne** [paritytech/cargo-contract#1291]
Upon work on #1290 I run into the issue that I can not submit instantiate extrinsic to the production chains. Astar and Shiden throw HTTP version error:
```
cargo contract instantiate --suri //Alice --url wss://rpc.astar.network --args false -x
ERROR: Rpc error: RPC error: Networking or low-level protocol error: Error in the WebSocket handshake: http version was not 1.1
```

When trying to upload & instantiate on Aleph Zero Main/Test-net `cargo-contract` fails to decode events:
```
ERROR: Could not decode `ContractResult::events`:
	Could not decode variant byte for `Option`:
		Not enough data to fill buffer


Caused by:
    0: Could not decode variant byte for `Option`:
       	Not enough data to fill buffer

    1: Not enough data to fill buffer
 ```

**Comment by ascjones** [comment]
Is this `cargo-contract` master you are using?

**Comment by ascjones** [comment]
`EventRecord` added the `events` field: https://github.com/paritytech/substrate/blob/7aacdf1755e63ba2b1aa3ace65aea063db421230/frame/contracts/primitives/src/lib.rs#L83.

So `cargo-contract` is expecting to decode that field, at the very least a `0` for None. Most likely the AZERO chain uses a legacy version of `pallet-contracts` which does not have this field.

Have you tried `cargo-contract` `3.0.1`?

**Comment by ascjones** [comment]
We should support different versions of `pallet-contracts`: see https://github.com/paritytech/cargo-contract/issues/1168

**Comment by SkymanOne** [comment]
> Is this `cargo-contract` master you are using? 

Yes

**Comment by DaddyDillZero** [comment]
Anyone knows the fix to this? For my case, it was working well with Aleph's testnet but not mainnet.

**Comment by DaddyDillZero** [comment]
> Possibly the testnet is running with a more recent version of `pallet_contracts` and the mainnet has an older, incompatible version?

So do I have to downgrade my cargo contract version for it to work? But if that's the case, then no one previously could call contracts through CLI?

**Comment by SkymanOne** [comment]
> So do I have to downgrade my cargo contract version for it to work? But if that's the case, then no one previously could call contracts through CLI?

Yes, you do need to downgrade since en/decoding is handled differently

**Comment by smiasojed** [comment]
With the PR https://github.com/paritytech/cargo-contract/pull/1399 we support different `pallet_contracts` versions.
