### ISSUE TITLE
ERROR: Access is denied. (os error 5)

### ISSUE THREAD

**Issue by z99988** [paritytech/cargo-contract#139]
I trying to create a substrate smart contract using the workshop reference material posted in
as described in https://substrate.dev/substrate-contracts-workshop/#/0/setup. 
I have installed all the dependencies on Windows 10 OS. 

**"cargo +nightly contract build" command fails after completing 3 steps ( [3/5] Optimizing wasm file) with the error message -ERROR: Access is denied. (os error 5).

Please help

**Comment by ascjones** [comment]
I have yet to test this on Windows so there are likely issues as you are experiencing. However we plan to fully support windows in the near future, see https://github.com/paritytech/cargo-contract/issues/36

**Comment by HCastano** [comment]
@z99988 this should be resolved now. Feel free to re-open if that's not the case.
