### ISSUE TITLE
Macro for generating contract API (like subxt)

### ISSUE THREAD

**Issue by jakubDoka** [paritytech/cargo-contract#1406]
**Is your feature request related to a problem? Please describe.**
When encoding contract call to be called trough subxt, I needed to dig into sourcecode of this repo to find a way to encode arguments. The API that is exposed in `transcoder` is rather dynamic.

**Describe the solution you'd like**
It would be nice to have a macro that takes `contract.json` and generates module with the contracts API that would make same signatures and functions contained in the `contract.json` but return a `Vec<u8>` to be passed as `call_data` to `subxt_generated_api::tx().contracts().call()`.

**Additional context**
I am planning to implement this for my project, though, if I could contribute it into more discoverable place, it would be amazing.

Optionally I could also extend the ink tutorial with section on how to call the smart contracts from rust code, it took quite some time to figure out and it might be useful to others.

**Comment by pmikolajczyk41** [comment]
you might want to have a look at https://github.com/Cardinal-Cryptography/ink-wrapper

**Comment by ascjones** [comment]
> you might want to have a look at https://github.com/Cardinal-Cryptography/ink-wrapper

Yes we recommend using this.

An alternative is to reference the contract as library with the `ink-as-dependency` feature, and you can use the contract ref for strongly typed message args encoding. This is what is used in cross contract calls and the `e2e` crate.
