### ISSUE TITLE
Unable to build a verifiable ink! flipper contract

### ISSUE THREAD

**Issue by ipapandinas** [paritytech/cargo-contract#1455]
**Describe the bug**

When trying to execute a verifiable build locally for the [flipper contract](https://github.com/paritytech/ink-examples/tree/main/flipper) from [ink-examples](https://github.com/paritytech/ink-examples) project, I face the following error:

```bash
cargo contract build --verifiable
 [==] Started the build inside the container: ink-verified-flipper-63196
 [==] Checking clippy linting rules
error: 'cargo-clippy' is not installed for the toolchain 'stable-x86_64-unknown-linux-gnu'
To install, run `rustup component add clippy`
 [==] Building cargo project
    Building...
    Building [=========================> ] 86/87: flipper(bin)
    Finished release [optimized] target(s) in 2m 33s
 [==] Post processing code
 [==] Generating metadata
   Compiling...
    Finished release [optimized] target(s) in 5m 52s
    Running `target/ink/release/metadata-gen`
 [==] Generating bundle
ERROR: Error decoding BuildResult:
 }

Caused by:
    expected value at line 1 column 1
```

**To Reproduce**
1. Build the [flipper contract](https://github.com/paritytech/ink-examples/tree/main/flipper) with the --verifiable flag:

`cargo contract build --verifiable`

**Expected behavior**
The expected response should contain metadata with the `paritytech/contracts-verifiable` image according to the [documentation](https://use.ink/basics/verification/contract-verification).

**Environment (please complete the following information):**
 - OS: MacOS M1 darwin
 - rust: 1.72.1
 - rust toolchain: 1.72-aarch64-apple-darwin
 - `cargo-contract` version: 4.0.0-rc.1
 - ink! version: 4.2.0

**Additional context**

I don't think the clippy error cause this issue since I also tried overriding the `paritytech/contracts-verifiable` image with clippy installed.

**Comment by SkymanOne** [comment]
This happens sometimes the old version of Docker Desktop client, try to update the client

**Comment by ipapandinas** [comment]
Thank you, that worked!
