### ISSUE TITLE
e2e tests fail on flipper contract that cargo contract creates

### ISSUE THREAD

**Issue by brunopgalvao** [paritytech/cargo-contract#1576]
**Describe the bug**
When I run `cargo contract` to create a contract I get the flipper template.
The flipper template that cargo contract creates fails for e2e testing.

The flipper template that cargo contract generates is different then the flipper code here:
- https://github.com/paritytech/ink-examples/tree/main/flipper
The e2e tests for the flipper code above works.

**To Reproduce**
1. Create a new contract using cargo contract
2. Run e2e tests

**Comment by smiasojed** [comment]
Hey @brunopgalvao,
please ensure that you use cargo-contract version 4.0.1 or later:
https://github.com/paritytech/cargo-contract/releases/tag/v4.0.1

The issue which you reported was present in version 4.0.0

**Comment by brunopgalvao** [comment]
Thanks @smiasojed !!

Confirmed. Working on `4.0.2`.
