### ISSUE TITLE
Give contract authors control over optimization passes

### ISSUE THREAD

**Issue by cmichi** [paritytech/cargo-contract#169]
## Motivation

In `src/cmd/build.rs` we currently pass the number of optimization passes `3` to `binaryen` by default. However, it is desirable to give contract authors control over this setting. Hence we want to expose it on the cli.

## ToDo

- [ ] `cargo contract build` should have an additional `--optimization-passes` parameter which makes this variable customizable.

**Comment by clearloop** [comment]
Hi @cmichi , we have a modification in #131 related to the opt passes, if there is any plan on the wasm optimization in `cargo-contract`, please ping us ( @patractlabs )

**Comment by ascjones** [comment]
In addition we could allow this to be configurable via a custom section in a contract's `Cargo.toml`.
