### ISSUE TITLE
generate-metadata failed because 0.19 bitvec is broken by 1.2 funty

### ISSUE THREAD

**Issue by RoyTimes** [paritytech/cargo-contract#176]
The error below can be reproduced by running `cargo +nightly contract generate-metadata`

```
error[E0034]: multiple applicable items in scope
   --> /Users/username/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/order.rs:476:7
    |
476 |             R::BITS,
    |                ^^^^ multiple `BITS` found
    |
```

It appears that funty1.2 made some breaking changes. So I guess either the author of funty change v1.2 to v2.0 , or temporarily force bitvec to use funty v1.1

ref: https://github.com/myrrlyn/funty/issues/3 
ref: https://github.com/bitvecto-rs/bitvec/issues/105

**Comment by RoyTimes** [comment]
Adding `funty = {version = "=1.1", default-features = false}` to `contracts/Cargo.toml` seems to temporarily fix it.

**Comment by athei** [comment]
```
funty v1.1.0
└── bitvec v0.20.1
    └── parity-scale-codec v2.0.0
        └── cargo-contract v0.8.0
```

This is an upstream issue and resolves itself once `funty` yanks its breaking minor version (or any other upstream package implements a hotfix) [1](https://github.com/paritytech/parity-scale-codec/pull/250)
