### ISSUE TITLE
Installed wasm-opt optimization not working

### ISSUE THREAD

**Issue by ascjones** [paritytech/cargo-contract#183]
Using locally installed `wasm-opt version 99 (version_73-1265-ga74bc72db)`

![image](https://user-images.githubusercontent.com/75586/108386713-cf66f980-7204-11eb-9506-d9385a76bbcd.png)

Discovered while testing https://github.com/paritytech/cargo-contract/pull/174, but it is also an issue on `master` (I did pull the latest this time!).

Possibly related to https://github.com/paritytech/cargo-contract/pull/179, but haven't done any troubleshooting yet.

**Comment by cmichi** [comment]
Ah lol, I had the same today. It's due to an outdated `wasm-opt` on your system. Just do an upgrade of `binaryen` and you should be fine!

**Comment by ascjones** [comment]
Built with https://github.com/WebAssembly/binaryen/commit/f7bfc85fae3bebf9ff818905c9bc6df51989ce70 which is the current `HEAD`

**Comment by cmichi** [comment]
I've created https://github.com/WebAssembly/binaryen/issues/3587.
