### ISSUE TITLE
Advise  adding commit hash info in version

### ISSUE THREAD

**Issue by atenjin** [paritytech/cargo-contract#188]
Similar to solc or Substrate, when someone execute `--version`, would contains the commit hash info:
```bash
-->$ solc --version
solc, the solidity compiler commandline interface
Version: 0.8.1+commit.df193b15.Linux.g++
```

```bash
-->$ ./target/debug/polkadot --version
polkadot 1.0.0-2ca35c3-x86_64-linux-gnu
```

Currently, cargo-contract has not released next version, and we (Redspot) need those features. So we advice to add the commit hash info for our 3rd parites to distinguish whether this cargo-contract is from `crates.io` or `github master`. Thanks.

**Comment by atenjin** [comment]
I have summit pr #189 for this

**Comment by cmichi** [comment]
Closing the issue now since we have merged the PR a while ago.
