### ISSUE TITLE
Evaluate usage of proc. macro for detecting binaryen installation

### ISSUE THREAD

**Issue by cmichi** [paritytech/cargo-contract#195]
In a discussion with @Robbepop this came up:

We should check if we can get rid of our `binaryen-as-dependency` feature using a compile-time evaluating proc. macro which checks if `binaryen` is already installed.

**Comment by Robbepop** [comment]
Did we already talk about a `build.rs` build file in order to do this job? Or is it not applicable here?

**Comment by cmichi** [comment]
I discussed it in the original PR description. It's not applicable:

>The build script is run (once) after the dependencies are built, so without time travel it can not add dependencies.

(from rust-lang/cargo#5499)

**Comment by cmichi** [comment]
I'm closing this issue as we have removed the `binaryen-as-dependency` feature in https://github.com/paritytech/cargo-contract/pull/251.
