### ISSUE TITLE
Installing cargo-contract via Cargo to update ink! results in errors

### ISSUE THREAD

**Issue by iorveth** [paritytech/cargo-contract#21]
Used command: `cargo install --git https://github.com/paritytech/cargo-contract --force`

![Screenshot from 2020-02-01 01-13-46](https://user-images.githubusercontent.com/18070359/73580992-66dd9b00-4490-11ea-88b3-7c860293f161.png)

**Comment by Robbepop** [comment]
Transferred issues from ink! repo.

**Comment by bedeho** [comment]
I get the same error.

**Comment by iorveth** [comment]
> I get the same error.

Temporary resolved my issue, installing cargo-contract with extrinsics features. 
cargo `install --git https://github.com/paritytech/cargo-contract cargo-contract --features extrinsics --force`
