### ISSUE TITLE
Optimizing wasm file

### ISSUE THREAD

**Issue by kenokenobingo** [paritytech/cargo-contract#213]
When compiling the default flipper contract (created with `cargo contract new flipper`) on macOS, I got the following error:

```
[3/5] Optimizing wasm file
ERROR: wasm-opt is not installed. Install this tool on your system in order to
reduce the size of your contract's Wasm binary.
See https://github.com/WebAssembly/binaryen#tools
```

So I installed `wasm-opt` via npm (`npm install wasm-opt -g`). Now I’m getting the following error:

```
[3/5] Optimizing wasm file
ERROR: No such file or directory (os error 2)
```

**Comment by 2075** [comment]
have a look here, maybe it helps: https://github.com/paritytech/cargo-contract/issues/215#issuecomment-790951169

**Comment by cmichi** [comment]
@kenokenobingo Are you using the latest `cargo-contract` version? You can make sure it's the most recent one via `cargo install --force cargo-contract`.

Could you post the output of `RUST_LOG=debug cargo contract build` (or the file `cargo-contract.log` from running `RUST_LOG=debug cargo contract build > cargo-contract.log 2>&1`)?

**Comment by kenokenobingo** [comment]
Thanks, @2075 and @cmichi! Installing `binaryen` with `npm` instead of Homebrew worked for me!
