### ISSUE TITLE
cargo +nightly contract build Error !

### ISSUE THREAD

**Issue by PolkaLink** [paritytech/cargo-contract#214]
Hello,  ive tried to fix this issue but i dont know how to or where it stems from. I followed instructions as per tutorial correctly, 
and when i ran the cargo +nightly test it was fine and It passed but when I came to use cargo +nightly contract build I recieved the below error when it was compiling on 105/106 compilation

error[E0277]: the trait bound `__ink_ConstructorDispatchEnum: parity_scale_codec::codec::WrapperTypeDecode` is not satisfied
   --> /c/Users/milker/pp/flipper/lib.rs:5:1
    |
5   | #[ink::contract]
    | ^^^^^^^^^^^^^^^^ the trait `parity_scale_codec::codec::WrapperTypeDecode` is not implemented for `__ink_ConstructorDispatchEnum`
    |
   ::: /home/milker/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_env-3.0.0-rc3/src/api.rs:465:8
    |
465 |     T: scale::Decode,
    |        ------------- required by this bound in `decode_input`
    |
    = note: required because of the requirements on the impl of `parity_scale_codec::codec::Decode` for `__ink_ConstructorDispatchEnum`
    = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `__ink_MessageDispatchEnum: parity_scale_codec::codec::WrapperTypeDecode` is not satisfied
   --> /c/Users/milker/pp/flipper/lib.rs:5:1
    |
5   | #[ink::contract]
    | ^^^^^^^^^^^^^^^^ the trait `parity_scale_codec::codec::WrapperTypeDecode` is not implemented for `__ink_MessageDispatchEnum`
    |
   ::: /home/milker/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_env-3.0.0-rc3/src/api.rs:465:8
    |
465 |     T: scale::Decode,
    |        ------------- required by this bound in `decode_input`
    |
    = note: required because of the requirements on the impl of `parity_scale_codec::codec::Decode` for `__ink_MessageDispatchEnum`
    = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `flipper`

To learn more, run the command again with --verbose.
ERROR: `"/home/milker/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo" "build" "--target=wasm32-unknown-unknown" "-Zbuild-std" "-Zbuild-std-features=panic_immediate_abort" "--no-default-features" "--release" "--target-dir=/c/Users/milker/pp/flipper/target"` failed with exit code: Some(101)

**Comment by PolkaLink** [comment]
j

**Comment by cmichi** [comment]
@PolkaLink Ubuntu has `binaryen` available as a package, I'm not sure about how it works with WSL though. You could try `sudo apt-get install binaryen`, under Ubuntu this would install the package.

**Comment by PolkaLink** [comment]
Yeh I've tried that and it tells me my binary package is upto date version 91
