### ISSUE TITLE
Binaryen package error

### ISSUE THREAD

**Issue by PolkaLink** [paritytech/cargo-contract#215]
Hi, 

During cargo contract build i recieve this error 

ERROR: The wasm-opt optimization failed.
A possible source of error could be that you have an outdated binaryen package installed.

Zero-fileld- memory 

My current version is 91. I require a version >98

I am on Windows 10 but I'm using wsl Ubuntu. 
How do I update binaryen?

**Comment by 2075** [comment]
try this:

```
rustup component add rust-src
npm install -g binaryen --force
cargo install --force cargo-contract
cargo +nightly contract build
```

works for me.

**Comment by PolkaLink** [comment]
This is how i fixed the binaryen issue (notice my npm file was missing)

$ sudo curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
$`sudo apt install nodejs`
$npm install -g binaryen --force

This gave me updated version of nodejs v12.16.3
and npm which was missing on ubuntu 6.14.4
and the Binaryen is now updated to Version 100

Then I ran

cargo install --force cargo-contract
cargo +nightly contract build
and all issues was fixed and the smart contract compiled
