### ISSUE TITLE
Add LLVM's opt tool to `cargo contract build`

### ISSUE THREAD

**Issue by Robbepop** [paritytech/cargo-contract#22]
At the moment ink! smart contracts have all their panic messages included in the data segment of the Wasm binary even though execution aborts upon panic and will never output any panic messages.

This is due to a "bug" between Rust and LLVM translation.
We can manually optimize this superflous data away with LLVM's `opt` tool.
The passes we need to enable from it are:
- `-deadargelim`: https://llvm.org/docs/Passes.html#deadargelim-dead-argument-elimination
- `-globaldce`: https://llvm.org/docs/Passes.html#globaldce-dead-global-elimination
Note that `opt` works on LLVM IR, not on Rust nor WebAssembly. So this needs some adjustments to the `cargo contract` build process.

The `opt` tool usage should be enabled by default, however, if it does not exist on a user machine the build process should simply do what it currently does (not use `opt`) and print a warning to the user stating that the resulting Wasm binary might not be optimal for the given reason.

**Comment by pepyakin** [comment]
Note, that I was using a matching versions of LLVM and rustc. I am not sure that it will work if the versions of rustc's LLVM and LLVM of opt mismatch.

**Comment by ascjones** [comment]
Can you provide a pseudo `build.sh` for this

**Comment by pepyakin** [comment]
I am afraid that I don't have anything at hand and the best info can be only found at the [original issue](https://github.com/rust-lang/rust/issues/47526).

**Comment by Robbepop** [comment]
This can be closed since we found a much better solution to solve the underlying problem via Xargo.
