### ISSUE TITLE
Compilation fails when lib.name and package.name are different

### ISSUE THREAD

**Issue by ii-ii-ii** [paritytech/cargo-contract#221]
When I set lib.name to be different from package.name, I get this error.
```
ERROR: Loading original wasm file 'erc20/contracts/target/ink/wasm32-unknown-unknown/release/erc20.wasm'

Caused by:
    Can't read from the file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
An unexpected error occurred:
```

I want to know if the compiled wasm file name is [package.name].wasm or [lib.name].wasm.

**Comment by ascjones** [comment]
I believe the compiled wasm file name is <lib.name>.wasm, but we expect it to be <package.name>.wasm. This is a bug we should fix, in the meantime they will have to be the same.

**Comment by ii-ii-ii** [comment]
> I believe the compiled wasm file name is <lib.name>.wasm, but we expect it to be <package.name>.wasm. This is a bug we should fix, in the meantime they will have to be the same.

Thanks for your reply. One more question, if package.name is erc20-fixed and lib.name is erc20_fixed, it still compiles successfully, but the wasm file name is erc20_fixed.wasm. After fixing this bug, what kind of filename will I get? erc20_fixed.wasm or erc20-fixed.wasm?

**Comment by ascjones** [comment]
It will be the same as in the lib name (`erc20_fixed`), as it is now.
