### ISSUE TITLE
contract delegator bug

### ISSUE THREAD

**Issue by NetGodFather** [paritytech/cargo-contract#224]
Edit code base on https://github.com/paritytech/ink/tree/master/examples/delegator 
Modify adder/lib.rs，Add code like this:

    #[ink(message)]
    pub fn x_inc(&mut self, by: i32) -> Result<(), Error>{
	    self.accumulator.inc(by);
	    Ok(())
	}

Compiling will report a large number of errors。

Add the following code again:

	#[derive(Debug, PartialEq, Eq, scale::Encode)]
	#[cfg_attr(feature = "std", derive(scale_info::TypeInfo))]
	pub enum Error {
	}

Compiling will return the following error:

	Compiling adder v3.0.0-rc3 (/private/var/folders/fx/y3j80rgn433961wkpcjq4_fr0000gn/T/cargo-contract_sUXlX7/adder)
	error[E0599]: the method `fire` exists for struct `CallBuilder<DefaultEnvironment, Set<ink_env::AccountId>, Unset<u64>, Unset<u128>, Set<ExecutionInput<ArgumentList<ink_env::call::utils::Argument<i32>, ArgumentList<ArgumentListEnd, ArgumentListEnd>>>>, Set<ReturnType<Result<(), adder::Error>>>>`, but its trait bounds were not satisfied
	   --> /Users/hezhiqun/Substrate/ink/examples/delegator/adder/lib.rs:54:9
	    |
	54  | /         pub fn x_inc(&mut self, by: i32) -> Result<(), Error>{
	55  | |             self.accumulator.inc(by);
	56  | |
	57  | |             Ok(())
	58  | |         }
	    | |_________^ method cannot be called on `CallBuilder<DefaultEnvironment, Set<ink_env::AccountId>, Unset<u64>, Unset<u128>, Set<ExecutionInput<ArgumentList<ink_env::call::utils::Argument<i32>, ArgumentList<ArgumentListEnd, ArgumentListEnd>>>>, Set<ReturnType<Result<(), adder::Error>>>>` due to unsatisfied trait bounds
	    |
	   ::: /Users/hezhiqun/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:241:1
	    |
	241 |   pub enum Result<T, E> {
	    |   --------------------- doesn't satisfy `_: adder::_::_parity_scale_codec::Decode`
	    |
	    = note: the following trait bounds were not satisfied:
	            `Result<(), adder::Error>: adder::_::_parity_scale_codec::Decode`

	error: aborting due to previous error

	For more information about this error, try `rustc --explain E0599`.
	error: could not compile `adder`

	To learn more, run the command again with --verbose.

**Comment by NetGodFather** [comment]
Compiles using Cargo Contract 0.8.0 and 0.10.0 give the same results

**Comment by atenjin** [comment]
... way not add derive `scale::Decode` for `Error`... I think the rust print log has already show the reason...

For the reason way other examples do not add `Decode` in Error, just because delegator is a multi-contracts example, the Adder is dependent by `Delegator` contract, thus when Delegator call Adder's function, the return type must could be decoded, so that in Delegator could decode the return value.

**Comment by NetGodFather** [comment]
Let me try to comment out either or both of these sentences

    #[derive(Debug, PartialEq, Eq, scale::Encode)]
    #[cfg_attr(feature = "std", derive(scale_info::TypeInfo))]

The same error is still reported

**Comment by NetGodFather** [comment]
Will

    #[derive(Debug, PartialEq, Eq, scale::Encode)]

Modified to

    #[derive(Debug, PartialEq, Eq, scale::Encode, scale::Decode)]

After that, the compilation was successful.  Thank you for @atenjin
