### ISSUE TITLE
deploy command not working

### ISSUE THREAD

**Issue by naps62** [paritytech/cargo-contract#227]
I'm trying to run `cargo contract deploy --suri //Alice`.

Using `canvas-node` v0.1.4, I get the following error:

```
❯ cargo contract deploy --suri //Alice
ERROR: Rpc error: Server responded to our request with an error: Error { code: ServerError(1002), message: "Verification Error: Execution failed: ApiError(\"Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature\")", data: Some(String("RuntimeApi(\"Execution failed: ApiError(\\\"Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature\\\")\")")) }

Caused by:
    0: Server responded to our request with an error: Error { code: ServerError(1002), message: "Verification Error: Execution failed: ApiError(\"Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature\")", data: Some(String("RuntimeApi(\"Execution failed: ApiError(\\\"Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature\\\")\")")) }
    1: Server error: Verification Error: Execution failed: ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature")
```

I'm unsure what to do here. I've seen this error multiple times, but all the links point to a FAQ page that seems to indicate I need to take care of my custom types. which doesn't seem to be the case here. Or am I missing something?

---

If using `canvas-node` from its master branch, instead I get an error about `put_code` not existing.
From my (limited) understanding, this is no longer supported by pallet-contracts, and `instantiateWithCode` should be used instead? any plans to support this in this package?

**Comment by ascjones** [comment]
Once we've got the new release of `subxt` out, we can update it here which should fix this https://github.com/paritytech/substrate-subxt/pull/248

**Comment by HCastano** [comment]
@ascjones is this still an issue?

**Comment by ascjones** [comment]
Yes it's still an issue. Will likely only be resolved once I resurrect https://github.com/paritytech/cargo-contract/pull/79, which is dependent on my current metadata work.

**Comment by ascjones** [comment]
Should be fixed now
