### ISSUE TITLE
Flaky CI on `master`

### ISSUE THREAD

**Issue by cmichi** [paritytech/cargo-contract#234]
The test `cmd::metadata::tests::generate_metadata` succeeds sometimes and fails at other times.

These are runs for the same commit:

* Success: https://gitlab.parity.io/parity/cargo-contract/-/jobs/864147
* Failure: https://gitlab.parity.io/parity/cargo-contract/-/jobs/864124

A re-run usually succeeds at some point. 

It fails at an assertion where the hash of the generated Wasm on the filesystem is compared against the hash written in the metadata `source.hash` field.

**Comment by ascjones** [comment]
Closed by #263
