### ISSUE TITLE
How to use json parser in contract ?

### ISSUE THREAD

**Issue by FleetingTimePaul** [paritytech/cargo-contract#238]
I want to use json parser in rust contract,  I try to use serd_json, but complie failed.  
who can tell me how to use json parser. Thanks!

**Comment by ascjones** [comment]
Probably need to set `default-features = false` for `no_std` support, see https://serde.rs/no-std.html.

What's the use case? Not sure that parsing json in a contract is the right thing to do.

**Comment by ascjones** [comment]
Also this is not an issue with `cargo-contract` so closing.
