### ISSUE TITLE
wasm-opt version error on contract build

### ISSUE THREAD

**Issue by rrybarczyk** [paritytech/cargo-contract#247]
This error has been replicated on both Arch Linux (by installing `binaryen` via `$ yay binaryen`) and OSX (by installing `binaryen` via `$ brew install binaryen`).

After installing `binaryen` with the preferred installation method,  running `$ cargo +nightly contract build` fails with the following error:

```
ERROR: Unable to extract version information from wasm-opt version 100.
Your wasm-opt version is most probably too old. Make sure you use a version >= 99.
```

However, the `wasm-opt` version installed is the latest:
```
$ wasm-opt --version
> wasm-opt version 100
```

I also tried building the tagged `wasm-opt` version 99, which confusingly installed `wasm-opt` version 98. When trying to build with this version, it expectedly does not work.

The work around to this is by using the unpreferred method of building `binaryen` as a dependency when installing cargo-contract:

```
cargo install --force --features binaryen-as-dependency cargo-contract
```

**Comment by netrikare** [comment]
It looks like wasm-opt version checking regex assumes additional string after version number. Solution:
change: 
`let re = Regex::new(r"wasm-opt version (\d+)\s+").unwrap();`
to:          
`let re = Regex::new(r"wasm-opt version (\d+)\s*+").unwrap();`

in [src/cmd/build.rs](https://github.com/paritytech/cargo-contract/blob/cacf2d54f79b8184520dafc790302710d7f087d9/src/cmd/build.rs#L496)

**Comment by cmichi** [comment]
Thanks @rrybarczyk and @netrikare! Sorry about the late response, just saw it this morning, easter collided with this ticket :see_no_evil:.

We just issued a new release which fixes this issue and will make some adaptions to our CI setup to catch stuff like this earlier.

You can update to the latest version via
```
cargo install cargo-contract --version ^0.11 --force --locked
```
