### ISSUE TITLE
How to print AccountId with ink_env::debug_println?

### ISSUE THREAD

**Issue by FleetingTimePaul** [paritytech/cargo-contract#258]
I want to debug_println the AccountId, but I can't convert the AccountId to string.

**Comment by cmichi** [comment]
@FleetingTimePaul This should work:
```
let caller = Self::env().caller();
let message = format!("thanks for instantiation {:?}", caller);
ink_env::debug_println(&message);
```
This example of the [`Greeter` contract](https://paritytech.github.io/ink/ink_lang_macro/attr.contract.html#interacting-with-the-contract-executor) might be interesting for your.
