### ISSUE TITLE
substrate_fixed::types::U64F64 not compile with ink! contract

### ISSUE THREAD

**Issue by frankli-dev** [paritytech/cargo-contract#307]
```
use fixed::{types::extra::U64, FixedU128};
```
With `FixedU128<U64>` (`U64F64`) type, I’m having compiling issue with ink contract.
```
ERROR: Validation of the Wasm failed.
ERROR: An unexpected panic function import was found in the contract Wasm.
This typically goes back to a known bug in the Rust compiler:
https://github.com/rust-lang/rust/issues/78744
As a workaround try to insert `overflow-checks = false` into your `Cargo.toml`.
This will disable safe math operations, but unfortunately we are currently not 
aware of a better workaround until the bug in the compiler is fixed.
ERROR: An unexpected import function was found in the contract Wasm: _ZN4core9panicking5panic17h20961de9fc8fe231E.
The only allowed import functions are those starting with one of the following prefixes:
seal, memory
```

Please help me to fix this issue (or please recommend me any other library to use fixed point number in ink contract)

**Comment by athei** [comment]
Did you follow the instructions in the error message?

```
As a workaround try to insert `overflow-checks = false` into your `Cargo.toml`.
```

**Comment by frankli-dev** [comment]
> Did you follow the instructions in the error message?
> 
> ```
> As a workaround try to insert `overflow-checks = false` into your `Cargo.toml`.
> ```

yeah, it doesn't help

**Comment by frankli-dev** [comment]
just realized that converting `f64` into `u128` causes the above compiling issue.

```
let v = 0f64;
return v as u128
```
```

**Comment by frankli-dev** [comment]
> Did you follow the instructions in the error message?
> 
> ```
> As a workaround try to insert `overflow-checks = false` into your `Cargo.toml`.
> ```

Ah, it compiles with 
```
[profile.release]
overflow-checks = false
```

I tried with profile.dev but it didn't work. What is the correct profile?

**Comment by athei** [comment]
`release` is the correct profile.

**Comment by frankli-dev** [comment]
And `FixedU128<U64>` is also compiling with `overflow-checks = false`

So I'm wondering which one is better.. FixedU128<U64> or f64?

Please let me know

**Comment by frankli-dev** [comment]
![image](https://user-images.githubusercontent.com/51565705/126525377-6c875aaa-45f0-48d4-8994-7a989dffd29d.png)
Oops the contracts are compiled. But it causes the error when I deploy to the local node.

If I remove the conversion (f64 -> u128), it doesn't cause the error.
```
(v as u128)
```

**Comment by frankli-dev** [comment]
Does this mean `overflow-checks = false` doesn't deploy things?

**Comment by athei** [comment]
It should deploy with or without overflow checks. This must be something else. Most likely an ink! node version mismatch.

**Comment by HCastano** [comment]
@frankli-dev are there any updates here?

**Comment by frankli-dev** [comment]
It works with `overflow-checks = false`.
