### ISSUE TITLE
Investigate binary size reduction techniques

### ISSUE THREAD

**Issue by cmichi** [paritytech/cargo-contract#310]
Follow-up from a comment by @burdges [here](https://github.com/paritytech/substrate/issues/9354#issuecomment-886266088).

> I just learned from https://github.com/johnthagen/min-sized-rust that some binary size reductions occur with
> 
> ```
> [profile.release]
> codegen-units = 1
> ```

The linked GitHub repository lists more ideas we should try.

**Comment by burdges** [comment]
Xargo is listed there too.  I donno if you can have testnet or mainnet profiles which both give release builds but optimized for build time and everything but build time.

**Comment by athei** [comment]
> Xargo is listed there too.

ink! is already doing that. It builds `libcore` from source to remove the formatting code from panic handlers.

**Comment by cmichi** [comment]
I just went through the whole list and found that we already apply every strategy in `cargo-contract`.
