### ISSUE TITLE
rename project name

### ISSUE THREAD

**Issue by taskooh** [paritytech/cargo-contract#35]
Do you have a plan to implement renaming the project name?

when  I create the ink!'s project with
```bash
cargo contract new xxx
```

`lib.rs` would be like this
```rust
/* snip */
#[ink::contract(version = "0.1.0")]
mod xxx {
    /* snip */
    struct Xxx {
        /* snip */
    }
    impl Xxx {
        /* snip */
    }
    /*snip/
}
```

but, error occurs when I rename the struct name to `Yyy`, and run `cargo contract generate-metadata`.
In order to fix this, I manually have to edit `.ink/abi-gen/main.rs`

```rust
/* snip */
#[ink::contract(version = "0.1.0")]
mod xxx {
    /* snip */
    struct Yyy {
        /* snip */
    }
    impl Yyy {
        /* snip */
    }
    /*snip/
}
```

```bash
error[E0412]: cannot find type `Xxx` in crate `contract`
 --> .ink/abi_gen/main.rs:2:26
  |
2 |     let abi = <contract::Xxx as ink_lang::GenerateAbi>::generate_abi();
  |                          ^^^ not found in `contract`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0412`.
error: could not compile `abi-gen`.
```

**Comment by ascjones** [comment]
Yes that is annoying. Will have a look at some point but it is not high priority at the moment. PRs welcome!

**Comment by Robbepop** [comment]
Partially solved by https://github.com/paritytech/cargo-contract/issues/39.

**Comment by ascjones** [comment]
This should be fixed by https://github.com/paritytech/cargo-contract/pull/58
