### ISSUE TITLE
Release `1.0` for stable `ink!` `3.0.0` 

### ISSUE THREAD

**Issue by ascjones** [paritytech/cargo-contract#353]
For when we release `ink!` `3.0`, we should make a compatible `1.0` release of `cargo-contract`.

**Comment by cmichi** [comment]
With this release we should streamline the terminology in `cargo-contract` as well. According to https://github.com/paritytech/ink/issues/690:

>We no longer want to use the terms deploy/initialize for instantiating a contract on-chain, instead we want to use one term consistently which is _instantiate_. 

>We still refer to a contract being "uploaded" to a chain, when its Wasm code blob is put on-chain.

**Comment by keneek** [comment]
Related to this topic, the current CLI release creates an `ink!` project with a different codec from the `contracts-node-runtime` example. When you build the project in the CLI, Cargo.toml shows:

```
scale = { package = "parity-scale-codec", version = "2.1", default-features = false, features = ["derive"] }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"], optional = true }
```

The `contracts-node-runtime` version `0.8.0` Cargo.toml` file shows

```
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0", default-features = false, features = ["derive"] }
```

**Comment by ascjones** [comment]
Indeed, we have not yet done a `cargo-contract` `0.18` release with the latest template. You can `cargo install --git https://github.com/paritytech/cargo-contract --force`
