### ISSUE TITLE
when i use cargo-contract contract call get err

### ISSUE THREAD

**Issue by sharkygg** [paritytech/cargo-contract#362]
i use branch aj-contract-call, please give some help.
@ascjones 
ERROR: missing field `storage` at line 1363 column 1

ink version  master  3.0.0-rc6, compiler cargo-contract v0.15.0
cargo-contract aj-contract-call

**Comment by ascjones** [comment]
Yes this is a known issue, I will try and fix it soon

**Comment by sharkygg** [comment]
> Yes this is a known issue, I will try and fix it soon

hello, when could I use new version?

**Comment by sharkygg** [comment]
hello, when could I use new version? @ascjones

**Comment by ascjones** [comment]
It should work now. 

Note that this work is still a work in progress, so don't expect it to always be working until it is merged.
