### ISSUE TITLE
Add pass that removes spurious panic import function

### ISSUE THREAD

**Issue by athei** [paritytech/cargo-contract#369]
In order to resolve https://github.com/paritytech/ink/issues/364 we should add a pass that removes the imported function and replaces all call sides by an `unreachable` instruction. This is OK because we assume that the intention of calling this function is to panic anyways.

It might prevent unwinding in cases that is enabled. However, we don't support unwinding anyways so it does not matter.

**Comment by cmichi** [comment]
As part of this issue the effect of those two PR's should be revoked:
https://github.com/paritytech/ink/pull/1034
https://github.com/paritytech/cargo-contract/pull/372

**Comment by athei** [comment]
Replaced by https://github.com/paritytech/ink/pull/1049
