### ISSUE TITLE
Remove `workspace` when building a contract

### ISSUE THREAD

**Issue by cmichi** [paritytech/cargo-contract#377]
In https://github.com/paritytech/ink/pull/1054 @xgreenx found that if the `[workspace]` is removed from a contract's `Cargo.toml` the size decreases potentially significantly.

We should have `cargo-contract` remove the `[workspace]` section before building the contract.

**Comment by xgreenx** [comment]
Adding of empty `[workspace]` ignores `[workspace]` from a parent. So it can be a solution=)
```rust
[workspace]
members = []
```

So I can handle that=)
