### ISSUE TITLE
Error decoding field RuntimeMetadataPrefixed.1

### ISSUE THREAD

**Issue by netrikare** [paritytech/cargo-contract#420]
Running ```cargo contract deploy --suri //Alice``` on `flipper` contract example, deploying to `substrate-contracts-node`, results in the following error.

```
ERROR: Scale codec error: Error decoding field RuntimeMetadataPrefixed.1

Caused by:
    Error decoding field RuntimeMetadataPrefixed.1
```
I am also not able to deploy this contract using polkadot.js.org app:
```
{
  Module: {
    index: 8
    error: 10
  }
}
```

**Comment by ascjones** [comment]
Most likely a metadata mismatch, please reopen the issue if you still have it.
