### ISSUE TITLE
Cannot install cargo-contract on apple silicon

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/cargo-contract#482]
I run the following cmd on`macOS 12.2.1 (21D62)  Darwin 21.3.0`
```
RUST_LOG=debug cargo +nightly install cargo-contract
```

But got error:

```
The following warnings were emitted during compilation:

warning: Git command failed with status: exit status: 128
warning: Could not find `.git/HEAD` searching from `/Users/yjhmelody/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-contract-1.1.0` upwards!

error: failed to run custom build command for `cargo-contract v1.1.0`

Caused by:
  process didn't exit successfully: `/var/folders/74/ygz83jwd73nb_xlwfn6ll6fw0000gn/T/cargo-install2YpZ16/release/build/cargo-contract-a8af2065df09269c/build-script-build` (exit status: 1)
  --- stdout
  cargo:warning=Git command failed with status: exit status: 128
  cargo:rustc-env=CARGO_CONTRACT_CLI_IMPL_VERSION=1.1.0-unknown-aarch64-macos
  cargo:warning=Could not find `.git/HEAD` searching from `/Users/yjhmelody/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-contract-1.1.0` upwards!
  Creating template zip: template_dir '/Users/yjhmelody/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-contract-1.1.0/templates/new', destination archive '/var/folders/74/ygz83jwd73nb_xlwfn6ll6fw0000gn/T/cargo-install2YpZ16/release/build/cargo-contract-c534b324d52ca7dd/out/template.zip'
  Done: /Users/yjhmelody/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-contract-1.1.0/templates/new written to /var/folders/74/ygz83jwd73nb_xlwfn6ll6fw0000gn/T/cargo-install2YpZ16/release/build/cargo-contract-c534b324d52ca7dd/out/template.zip

  --- stderr
  Encountered error: '"/Users/yjhmelody/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-contract-1.1.0/ink_linting/_Cargo.toml"' does not exist
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-contract v1.1.0`, intermediate artifacts can be found at `/var/folders/74/ygz83jwd73nb_xlwfn6ll6fw0000gn/T/cargo-install2YpZ16`
```

**Comment by athei** [comment]
Works on stable for me. Why would you try to compile it with nightly?

**Comment by athei** [comment]
Works on my Mac Studio with a native toolchain. Please make sure to follow https://github.com/paritytech/cargo-contract#installation in order to install all necessary dependencies. Also, try to compile with stable. There is no reason to compile this crate with nightly.

**Comment by ascjones** [comment]
> Works on my Mac Studio with a native toolchain

:muscle:

**Comment by pencoa** [comment]
I follow the  https://github.com/paritytech/cargo-contract#installation step by step. It works on my Ubuntu Server, but still build failed on my Mac.  macOS Monterey 12.3.1   1.6 GHz Intel Core i5

```
warning: Git command failed with status: exit status: 128
warning: Could not find `.git/HEAD` searching from `/Users/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/cargo-contract-1.2.0` upwards!

error: failed to run custom build command for `cargo-contract v1.2.0`

Caused by:
  process didn't exit successfully: `/var/folders/gx/5hzgzhkj5yx_42_6fhgfs3_80000gn/T/cargo-installW6zOdb/release/build/cargo-contract-4cace80b1f387d9e/build-script-build` (exit status: 1)
  --- stdout
  cargo:warning=Git command failed with status: exit status: 128
  cargo:rustc-env=CARGO_CONTRACT_CLI_IMPL_VERSION=1.2.0-unknown-x86_64-macos
  cargo:warning=Could not find `.git/HEAD` searching from `/Users/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/cargo-contract-1.2.0` upwards!
  Creating template zip: template_dir '/Users/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/cargo-contract-1.2.0/templates/new', destination archive '/var/folders/gx/5hzgzhkj5yx_42_6fhgfs3_80000gn/T/cargo-installW6zOdb/release/build/cargo-contract-9cf715a18840e31e/out/template.zip'
  Done: /Users/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/cargo-contract-1.2.0/templates/new written to /var/folders/gx/5hzgzhkj5yx_42_6fhgfs3_80000gn/T/cargo-installW6zOdb/release/build/cargo-contract-9cf715a18840e31e/out/template.zip
  Setting cargo working dir to '/Users/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/cargo-contract-1.2.0/ink_linting'
  Invoking cargo: "cargo" "build" "--release" "--locked" "--target-dir=/var/folders/gx/5hzgzhkj5yx_42_6fhgfs3_80000gn/T/cargo-installW6zOdb/release/build/cargo-contract-9cf715a18840e31e/out" "--manifest-path=/Users/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/cargo-contract-1.2.0/ink_linting/Cargo.toml"

  --- stderr
  error: invalid channel name '# This file corresponds to the `rust-toolchain` file used for the `dylint` examples here:' in '/Users/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/cargo-contract-1.2.0/ink_linting/rust-toolchain'
  error: caused by: invalid toolchain name: '# This file corresponds to the `rust-toolchain` file used for the `dylint` examples here:'
  Encountered error: `"cargo" "build" "--release" "--locked" "--target-dir=/var/folders/gx/5hzgzhkj5yx_42_6fhgfs3_80000gn/T/cargo-installW6zOdb/release/build/cargo-contract-9cf715a18840e31e/out" "--manifest-path=/Users/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/cargo-contract-1.2.0/ink_linting/Cargo.toml"` failed with exit code: Some(1)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-contract v1.2.0`, intermediate artifacts can be found at `/var/folders/gx/5hzgzhkj5yx_42_6fhgfs3_80000gn/T/cargo-installW6zOdb`

Caused by:
  build failed
```

**Comment by athei** [comment]
Your rustup is too old: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

**Comment by pencoa** [comment]
> rustup default nightly-2022-05-05
I set rustup to the latest version, the error message is still the same.

**Comment by athei** [comment]
It is about the rustup version itself. Not the version of the toolchain. Have you read the article I linked?

**Comment by pencoa** [comment]
> It is about the rustup version itself. Not the version of the toolchain. Have you read the article I linked?

Sure, this command alse set default toolchain as nightly-2022-05-05. According to https://rust-lang.github.io/rustup/overrides.html#default-toolchain

**Comment by pencoa** [comment]
> It is about the rustup version itself.

Could you please list your rustup version used to build cargo-contract v1.2.0 or v1.3.0 successfully?

**Comment by meetAssassin** [comment]
> I run the following cmd on`macOS 12.2.1 (21D62) Darwin 21.3.0`
> 
> ```
> RUST_LOG=debug cargo +nightly install cargo-contract
> ```
> 
> But got error:
> 
> ```
> The following warnings were emitted during compilation:
> 
> warning: Git command failed with status: exit status: 128
> warning: Could not find `.git/HEAD` searching from `/Users/yjhmelody/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-contract-1.1.0` upwards!
> 
> error: failed to run custom build command for `cargo-contract v1.1.0`
> 
> Caused by:
>   process didn't exit successfully: `/var/folders/74/ygz83jwd73nb_xlwfn6ll6fw0000gn/T/cargo-install2YpZ16/release/build/cargo-contract-a8af2065df09269c/build-script-build` (exit status: 1)
>   --- stdout
>   cargo:warning=Git command failed with status: exit status: 128
>   cargo:rustc-env=CARGO_CONTRACT_CLI_IMPL_VERSION=1.1.0-unknown-aarch64-macos
>   cargo:warning=Could not find `.git/HEAD` searching from `/Users/yjhmelody/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-contract-1.1.0` upwards!
>   Creating template zip: template_dir '/Users/yjhmelody/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-contract-1.1.0/templates/new', destination archive '/var/folders/74/ygz83jwd73nb_xlwfn6ll6fw0000gn/T/cargo-install2YpZ16/release/build/cargo-contract-c534b324d52ca7dd/out/template.zip'
>   Done: /Users/yjhmelody/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-contract-1.1.0/templates/new written to /var/folders/74/ygz83jwd73nb_xlwfn6ll6fw0000gn/T/cargo-install2YpZ16/release/build/cargo-contract-c534b324d52ca7dd/out/template.zip
> 
>   --- stderr
>   Encountered error: '"/Users/yjhmelody/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-contract-1.1.0/ink_linting/_Cargo.toml"' does not exist
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `cargo-contract v1.1.0`, intermediate artifacts can be found at `/var/folders/74/ygz83jwd73nb_xlwfn6ll6fw0000gn/T/cargo-install2YpZ16`
> ```

Did you find any solution? I'm facing same error on my Windows

**Comment by cmichi** [comment]
@meetAssassin This is a very old issue, are you getting a similar error on a recent version of `cargo-contract`? If so, could you open a new issue with the details?
