### ISSUE TITLE
How do I pass in Vec arguments to constructor?

### ISSUE THREAD

**Issue by HCastano** [paritytech/cargo-contract#517]
My ink! constructor has the following signature:

```rust
pub fn new(requirement: u32, mut owners: Vec<AccountId>) -> Self
```

I've been trying to instantiate it but haven't been able to figure out how to pass in
`Vec` arguments. Some of my attempts include:

```
ink on  master [$] via 🦀 v1.62.0-nightly
❮ cargo contract instantiate \
       --constructor new \
       --args 1 [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY] \
       --suri //Alice \
       --manifest-path ./examples/multisig/Cargo.toml
ERROR: Failed to read from [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]

Caused by:
    No such file or directory (os error 2)
```

```
...
       --args 1 "[5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]" \
...
ERROR: Failed to read from [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]

Caused by:
    No such file or directory (os error 2)
```

```
...
       --args 1 \[5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]\ \
...
ERROR: Failed to read from [5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]

Caused by:
    No such file or directory (os error 2)
```

```
...
       --args 1 \"\[5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY\]\" \
...
ERROR: Failed to read from "[5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY]"

Caused by:
    No such file or directory (os error 2)
```

**Comment by ascjones** [comment]
I did a related fix in #519, but that is not the issue you are having here.

It now "works on my machine", however I remember that you are using `zsh` which from [cursory research ](https://zsh.sourceforge.io/Guide/zshguide05.html) interprets sqaure brackets as an array,

I've installed `zsh` on my machine, and the following two solutions work for me:

escaping: ` --args 2 \[5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY\] \`
quotation marks: `--args 2 "[5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY, 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty]"`

Can you try again with those two and see if it works now?
