### ISSUE TITLE
Extract helper functions to library?

### ISSUE THREAD

**Issue by lephyrius** [paritytech/cargo-contract#529]
I find these files extremely useful to the point that I have put them unaltered into my project. It's for transcoding call extrinsics. 
It would be useful to extract them into its own library:
https://github.com/paritytech/cargo-contract/blob/master/src/cmd/extrinsics/mod.rs#L117
https://github.com/paritytech/cargo-contract/blob/master/src/cmd/extrinsics/call.rs
https://github.com/paritytech/cargo-contract/tree/master/src/cmd/extrinsics/transcode

**Comment by ascjones** [comment]
It's a good idea and indeed they were originally part of a separate crate. I made them inline to speed up the initial development process, but now they have stablilized I will look at extracting this part again.

**Comment by fbielejec** [comment]
closed in #597 ?
