### ISSUE TITLE
Add `cargo encode` command

### ISSUE THREAD

**Issue by athei** [paritytech/cargo-contract#573]
The reverse function of `cargo decode` should also exist. I think we don't need to support events here. Only `message` and `constructor`.

```
cargo encode --type message --name "flip" --arg true --arg "lol" flipper.{json,contract}
cargo encode --type constructor --name "new" --arg false flipper.{json,contract}
```

Please note that this functionality already exists as part of calling contracts with `cargo contract call`.

**Comment by ascjones** [comment]
Looks to be closed by https://github.com/paritytech/cargo-contract/pull/998
