### ISSUE TITLE
ERROR: Failed to find CodeStored event

### ISSUE THREAD

**Issue by forgetso** [paritytech/cargo-contract#589]
The error `Failed to find CodeStored event` is always emitted when a contract is instantiated using this command:

`cargo contract instantiate $WASM --args $CONTRACT_ARGS --constructor $CONSTRUCTOR --suri $SURI --value $ENDOWMENT --url '$ENDPOINT:$PORT'"`

The error is emitted from:

https://github.com/paritytech/cargo-contract/blob/2961428c231b8203935f9e26142b00015f5d19c2/src/cmd/extrinsics/instantiate.rs#L290-L295

It seems irrelevant whether the `CodeStored` event is emitted as the contract works ok.

**Comment by ascjones** [comment]
Yes indeed this is a bug, if the code has already been uploaded then it should not expect the `CodeStored` event
