### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by ascjones** [paritytech/cargo-contract#6]

**Comment by TriplEight** [comment]
any specific jobs you want to be there besides obvious `cargo build --release` and `cargo test --release`?

**Comment by ascjones** [comment]
That should be good to start with. Perhaps also a `fmt` job like https://github.com/paritytech/ink/blob/master/.gitlab-ci.yml#L127

**Comment by ascjones** [comment]
Longer term, would it be possible to spin up a `substrate` node docker instance in order to run integration tests e.g. (https://github.com/paritytech/cargo-contract/blob/master/src/cmd/deploy.rs#L100)?

**Comment by TriplEight** [comment]
Basic CI implemented https://github.com/paritytech/cargo-contract/pull/16

Integration tests will happen here: https://gitlab.parity.io/parity/srml-contracts-waterfall/
