### ISSUE TITLE
Generate metadata for sub-contracts in multi contract workspace

### ISSUE THREAD

**Issue by ascjones** [paritytech/cargo-contract#60]
Following on from https://github.com/paritytech/cargo-contract/pull/58, we should support generating of metadata for the non-root contract in a multi contract workspace.

For example, the [`delegator`](https://github.com/paritytech/ink/tree/master/examples/delegator) example hosts multiple contracts which are dependencies of the main contract.

## Proposal
- All metadata files will be written to the `target` directory of the workspace root, with the file name the same as the contract module name e.g. `delegator.json`, `incrementer.json` etc.
- `cargo contract generate-metadata` in the [root workspace dir](https://github.com/paritytech/ink/tree/master/examples/delegator) generates just the metadata for the root contract (in this case the `delegator`
- Sub contracts: e.g `cd adder && cargo contract generate-metadata` generates just the metadata for that sub contract.
- Alternatively `cargo contract generate-metadata -p adder` from the root does the same, mirroring `cargo` functionality.
- `cargo contract generate-metadata --all` will generate metadata files for all contracts in the workspace, e.g. `delegator.json, adder.json, subber.json`

## Implementation notes

- Need to auto remove the `ink-as-dependency` feature in the root workspace manifest for the sub contracts

**Comment by ii-ii-ii** [comment]
hi, I would like to know if this issue is solved. Because I'm working on multiple contracts and I'll have some trouble if I can't generate abi for sub-contracts.

**Comment by ascjones** [comment]
It's not solved yet. It should still work if you run `cargo-contract` from a sub contract's directory, or use the `--manifest-path` argument

**Comment by ii-ii-ii** [comment]
When I try to execute `cargo +nightly contract build` in a subdirectory I get an error:

```
error[E0463]: can't find crate for `contract`
 --> .ink/metadata_gen/main.rs:1:1
  |
1 | extern crate contract;
  | ^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `metadata-gen`

To learn more, run the command again with --verbose.
```

It can get a wasm file, but cannot generate abi. Using `--manifest-path` also gives the same error

**Comment by ascjones** [comment]
My mistake, I thought it would have worked. I'll look at implementing this soon.
