### ISSUE TITLE
Not able to generate the metadata for the contract

### ISSUE THREAD

**Issue by satyamakgec** [paritytech/cargo-contract#67]
After running `cargo contract generate-metadata` I am getting this error

```
error[E0599]: no method named `sign` found for struct `ed25519_dalek::Keypair` in the current scope
   --> /Users/satyamagrawal/.cargo/git/checkouts/substrate-7e08433d4c370a21/b161460/primitives/core/src/ed25519.rs:497:18
    |
497 |         let r = self.0.sign(message).to_bytes();
    |                        ^^^^ method not found in `ed25519_dalek::Keypair`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use ed25519_dalek::Signer;`

error[E0599]: no function or associated item named `from_bytes` found for struct `ed25519_dalek::Signature` in the current scope
   --> /Users/satyamagrawal/.cargo/git/checkouts/substrate-7e08433d4c370a21/b161460/primitives/core/src/ed25519.rs:516:45
    |
516 |         let sig = match ed25519_dalek::Signature::from_bytes(sig) {
    |                                                   ^^^^^^^^^^
    |                                                   |
    |                                                   function or associated item not found in `ed25519_dalek::Signature`
    |                                                   help: there is an associated function with a similar name: `to_bytes`
    |
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use ed25519_dalek::ed25519::signature::Signature;`

error[E0599]: no method named `verify` found for struct `ed25519_dalek::PublicKey` in the current scope
   --> /Users/satyamagrawal/.cargo/git/checkouts/substrate-7e08433d4c370a21/b161460/primitives/core/src/ed25519.rs:521:20
    |
521 |         match public_key.verify(message.as_ref(), &sig) {
    |                          ^^^^^^ this is an associated function, not a method
    |
    = note: found the following associated functions; to be used as methods, functions must have a `self` parameter
note: the candidate is defined in the trait `crypto::Pair`
   --> /Users/satyamagrawal/.cargo/git/checkouts/substrate-7e08433d4c370a21/b161460/primitives/core/src/crypto.rs:821:2
    |
821 |     fn verify<M: AsRef<[u8]>>(sig: &Self::Signature, message: M, pubkey: &Self::Public) -> bool;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope; perhaps add a `use` for it:
            `use ed25519_dalek::Verifier;`
help: use associated function syntax instead
    |
521 |         match ed25519_dalek::PublicKey::verify(message.as_ref(), &sig) {
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: disambiguate the associated function for the candidate
    |
521 |         match crypto::Pair::verify(public_key, message.as_ref(), &sig) {
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `sp-core`.
```
but `cargo contract build` works fine. 

Code - https://github.com/PolymathNetwork/Polymesh/blob/MESH-1133/examples-se/contracts/examples/RuntimeInteraction/lib.rs
cargo-contract version - v0.6.1
ink! version - v2.1.0
substrate version - rc4

**Comment by satyamakgec** [comment]
[pasting the riot chat]
from @riusricardo 

There is a workaround that can help you by modifying the cargo.lock file.
Change this package:
```
[[package]]
name = "ed25519-dalek"
version = "1.0.0-pre.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "21a8a37f4e8b35af971e6db5e3897e7a6344caa3f92f6544f88125a1f5f0035a"
dependencies = [
 "curve25519-dalek",
 "ed25519",
 "rand 0.7.3",
 "serde",
 "sha2 0.8.2",
 "zeroize",
]
```
To:

```
[[package]]
name = "ed25519-dalek"
version = "1.0.0-pre.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "978710b352437433c97b2bff193f2fb1dfd58a093f863dd95e225a19baa599a2"
dependencies = [
 "clear_on_drop",
 "curve25519-dalek",
 "rand 0.7.3",
 "sha2",
]
```
This is fixed in rc5, but as you are using rc4 you need to use this patch.

from @satyamakgec
It didn't work even I tried using `1.0.0-pre.3` explicitly in the cargo.toml but nothing works.

**Comment by riusricardo** [comment]
@satyamakgec I can reproduce your issue. The solution I tried is very hacky and manual but it worked.
The same workaround fixes the issue, but it needs to be applied to a Cargo.lock file that is generated in a temporary directory when building the metadata.
```
cargo contract generate-metadata --verbose
```
Is expanded to something like this:
```
cargo run --package abi-gen --manifest-path=/tmp/.cargo-contract_BePiu9/Cargo.toml --target-dir=/home/ubuntu/tests/Polymesh/contracts/examples/RuntimeInteraction/target --release --verbose
```
Where ` --manifest-path=/tmp/.cargo-contract_<######>/Cargo.toml` is the temporary directory that gets deleted after a successful or failed build. The error happens in this directory. This is why fixing the Cargo.lock in the contract's directory isn't enough.

1) Run `cargo contract generate-metadata --verbose`
2) After the first build fails, you will have a Cargo.lock in the contract's directory. Apply the workaround on this file.
3) Run the same command a second time `cargo contract generate-metadata --verbose` and break the build (ctrl + c). This will preserve the new temp directory.
4) Find out the name of your new temp dir. `/tmp/.cargo-contract_<######>`
5) Run the final command from the contract's directory and pointing the `--manifest-path` to your temp directory.
```
cargo run --package abi-gen --manifest-path=/tmp/.cargo-contract_<######>/Cargo.toml --target-dir=/home/ubuntu/tests/Polymesh/contracts/examples/RuntimeInteraction/target --release --verbose
```

**Comment by satyamakgec** [comment]
Thanks @riusricardo for doing all the hard work. It works as you suggested.

You already know it is manual approach. Do you plan to resolve this in the coming version of the cargo-contract?

**Comment by ascjones** [comment]
It's already resolved with the release of substrate `rc5`. 

I just had a quick look at the example, and maybe you could remove the dependency on substrate? I could only find the `sp_runtime::traits::Member` trait being used: https://github.com/PolymathNetwork/Polymesh/blob/MESH-1133/examples-se/contracts/examples/custom-ink-env-types/src/calls.rs#L4. 

Also in the (not yet released, but can install from github) there is an option to not use the tmp di `-Zoriginal-manifest` during build so would avoid having to do the above hack.

**Comment by satyamakgec** [comment]
@ascjones Other dependencies are added to avoid the `sp-io` error this is why I used some special features of the sp-io https://github.com/PolymathNetwork/Polymesh/blob/1274ea1915ed672d9e842d2f5386805a56bfd98a/contracts/examples/custom-ink-env-types/Cargo.toml#L16

I think because of the same reason you guys added these type dependencies here https://github.com/paritytech/ink-types-node-runtime/blob/master/Cargo.toml#L25. 

If I used `-Zoriginal-manifest` this functionality by fetching the latest cargo-contract then it may break the contract functionality on the susbtrate side or ink! due to the older version I am using ?

**Comment by ascjones** [comment]
> I think because of the same reason you guys added these type dependencies here https://github.com/paritytech/ink-types-node-runtime/blob/master/Cargo.toml#L25.

The substrate dependencies are used there just to import the `Address` type to avoid copying its custom decoding. However if I'm not missing something, you are not using this type or any others - so you should be able to remove all substrate dependencies entirely.

> If I used -Zoriginal-manifest this functionality by fetching the latest cargo-contract then it may break the contract functionality on the susbtrate side or ink! due to the older version I am using ?

If you pull the latest version, then yes it won't work. If you install from this commit https://github.com/paritytech/cargo-contract/commit/06a9e8dde87e608a98e9bed3b4ee436e20fede14 then it *might* still work with the old version of `ink!`.

Having said that I would try and remove the substrate dependencies first.
