### ISSUE TITLE
Solang support

### ISSUE THREAD

**Issue by ascjones** [paritytech/cargo-contract#68]
Might be nice to be able to build contracts written in solidity, by invoking https://github.com/hyperledger-labs/solang. 

e.g. `cargo contract build flipper.sol` would detect the `sol` extension and attempt to build using `solang`. If the `solang` binary is not installed the user could be prompted to install it via https://solang.readthedocs.io/en/latest/installing.html.

**Comment by atenjin** [comment]
Interesting. But I think we may do not need cargo contract to call Solang to compile. cargo-contract just  needs to take charge of ink self maybe better.

**Comment by xermicus** [comment]
@ascjones I self-assigned this to me, it came up in our solang daily stand-up. I can look at potential solutions for this (after we fix the metadata issue on solang). This would be nice to have! TBH. this could also work the other way round (e.g. if we could somehow make use of cargo-contract in solang itself).

CC @extraymond

**Comment by extraymond** [comment]
Thanks! I think it'll be mostly useful for use cases including extrinsics and rpcs parts where pallet-contracts are assume, which solang is.

**Comment by ltfschoen** [comment]
> xermicus

@xermicus i was just wondering if you've had time to start on this? i'm eager to try to do it all or help you finish it.
whilst i'm at it i may as well add [Vyper](https://docs.vyperlang.org/) support too

**Comment by xermicus** [comment]
No I currently don't work on this

**Comment by ltfschoen** [comment]
i was just thinking about this, maybe in the CLI there could be options like `--solidity-wasm` and `--solidity-evm` to allow the user to also choose what compiler to use if it detects any .sol files so they may generate either WASM or EVM bytecode, and in the future eWASM like i mentioned here https://substrate.stackexchange.com/questions/8721/how-to-interact-between-a-smart-contract-written-in-solidity-from-a-smart-contra

**Comment by ltfschoen** [comment]
> @ltfschoen I answered regarding cross contracts call directly in the SE question.
> 
> > choose what compiler to use if it detects any .sol files so they may generate either WASM or EVM bytecode
> 
> Right now I don't think this is useful.
> 
> * Cross calls between different runtimes is complex and wouldn't work on most chains
> * If the Solidity contract compiles fine with Solang, I see no reason to use an EVM version instead
> * Many real world contracts require small changes to compile with Solang (which may break compatibility with solc)
> * eWasm is dead in the water and most likely not happening. And even if it would, the contracts would not work just like that on the contracts pallet.
> 
> That said, do you have a specific use case in mind?

in addition to compiling the Solidity contracts to WASM using Solang, i was going to add functionality to compile Solidity contracts to EVM since some chains like Moonbeam only support EVM smart contracts, whereas other chains like Astar support WASM.

so a use case would be using cargo-contract to compile a Solidity contract that uses a Moonbeam Solidity Precompile https://docs.moonbeam.network/builders/pallets-precompiles/precompiles (that exposes Substrate functionality like Democracy or Staking) and compiles to EVM

**Comment by ltfschoen** [comment]
@xermicus I created a PR here https://github.com/paritytech/cargo-contract/pull/1137
