### ISSUE TITLE
Add `--output-json` for `call` and `instantiate` commands

### ISSUE THREAD

**Issue by fbielejec** [paritytech/cargo-contract#682]
Have you considered making the tool spit out some output with a schema, say JSON? This would help a lot when using the tool in various automated pipelines.

**Comment by cmichi** [comment]
There is 
```
cargo contract build --release --skip-linting --output-json
```

Does this already help you? If not, could you specify what info you would like to see in there?

**Comment by fbielejec** [comment]
I should have been clearer:  I rather meant the stdout of the call or instantiate commands.

**Comment by ascjones** [comment]
Yes that would indeed be useful. Could you please update the issue title and description?
