### ISSUE TITLE
Problem with "dylink-link"

### ISSUE THREAD

**Issue by goodelita1** [paritytech/cargo-contract#694]
I can't install cargo-contract  

- I use `cargo install cargo-contract --force`
and i have 
`You can install it by executing `cargo install dylint-link`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-contract v1.5.0`, intermediate artifacts can be found at `/var/folders/fj/4b39y4p90jgdrv1q5tf2gw9m0000gn/T/cargo-installBi6fRQ`

- when i use `cargo install dylink-link` I have error like this

`error: failed to run custom build command for `cargo-contract v1.5.0`
  error: linking with `dylint-link` failed: exit status: 1
    = note: Error: environment variable not found: RUSTUP_TOOLCHAIN
  error: could not compile `memchr` due to previous error
  Encountered error: `"cargo" "build" "--release" "--locked" "--target-dir=/var/folders/jd/73lyz6310dn537m46l1mvpc80000gn/T/cargo-installvzE2rK/release/build/cargo-contract-381c578b21eede4a/out" "--manifest-path=/Users/anymacstore/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-contract-1.5.0/ink_linting/Cargo.toml"` failed with exit code: Some(101)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-contract v1.5.0`, intermediate artifacts can be found at `/var/folders/jd/73lyz6310dn537m46l1mvpc80000gn/T/cargo-installvzE2rK`
     Summary Failed to install --skip, -linking, cargo-contract (see error(s) above).
error: some crates failed to install
anymacstore@AnyMacs-MacBook-Pro ~ % rustup default
nightly-x86_64-apple-darwin (default)`

Can somebody help me plz ?

**Comment by ascjones** [comment]
What version of `rustup` are you using, can you do `rustup -vV` and post the result here?

**Comment by goodelita1** [comment]
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active rustc version is rustc 1.65.0-nightly (34a6cae28 2022-08-09)

**Comment by goodelita1** [comment]
> What version of `rustup` are you using, can you do `rustup -vV` and post the result here?

rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active rustc version is rustc 1.65.0-nightly (34a6cae28 2022-08-09)

**Comment by ascjones** [comment]
I have just tried this on my wife's macbook and it works with `rustup 1.25.1 (bb60b1e89 2022-07-12)`.

One difference is it is built with the `stable` toolchain `rustc 1.63.0 (4b9...`

Also I first ran `cargo install cargo-dylint dylint-link`, did you also install `cargo-dylint`?

**Comment by ascjones** [comment]
> do you know any way to skip it maybe)

At the moment it is a prerequisite unfortunately, but we have it in mind to make this optional

**Comment by goodelita1** [comment]
> > do you know any way to skip it maybe)
> 
> At the moment it is a prerequisite unfortunately, but we have it in mind to make this optional

Okey I used cargo install cargo-dylint dylint-link, but the error is still the same

**Comment by goodelita1** [comment]
> I have just tried this on my wife's macbook and it works with `rustup 1.25.1 (bb60b1e89 2022-07-12)`.
> 
> 
> 
> One difference is it is built with the `stable` toolchain `rustc 1.63.0 (4b9...`
> 
> 
> 
> Also I first ran `cargo install cargo-dylint dylint-link`, did you also install `cargo-dylint`?

After install this in my second Mac everything goes good I think it's something with my macbook( `cargo install cargo-dylint dylint-link`

**Comment by ascjones** [comment]
> After install this in my second Mac everything goes good I think it's something with my macbook( cargo install cargo-dylint dylint-link

I initially had some other issues while installing these. Clearing out `~/.cargo` ($CARGO_HOME) did the trick for me (except the `bin` dir). So something to try on your macbook

**Comment by goodelita1** [comment]
> > After install this in my second Mac everything goes good I think it's something with my macbook( cargo install cargo-dylint dylint-link
> 
> 
> 
> I initially had some other issues while installing these. Clearing out `~/.cargo` ($CARGO_HOME) did the trick for me (except the `bin` dir). So something to try on your macbook


Yep you are right
- I uninstalled `.cargo` with:
`sudo rm -r .cargo` 
- then I went to:
`cd /usr/local/bin`
- Deleted here:
`rm cargo rustc`
- Than I reinstalled rust:
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
- Again reinstalled `dylint`:
`cargo install cargo-dylint dylink-link` 
- And run:
`cargo install cargo-contract --force`
