### ISSUE TITLE
Add optional verbose output to `cargo contract build`

### ISSUE THREAD

**Issue by expenses** [paritytech/cargo-contract#7]
`cargo contract build` can take quite a while to build things, but it's output is quite quiet:
```
 [1/3] Collecting crate metadata
 [2/3] Building cargo project
 [3/3] Post processing wasm file
	Your contract is ready.
You can find it here:
...
```

It would be great to have a `-v`/`--verbose` flag that prints more often.

**Comment by ascjones** [comment]
Closed by #33
