### ISSUE TITLE
`rust-src` component not found.

### ISSUE THREAD

**Issue by aniiantt** [paritytech/cargo-contract#70]
When I execute cargo +nightly Contract build,  I got an error.
```
 `rust-src` component not found. Run `rustup component add rust-src`.
```
But I think I have rust-src installed, and the `rustup component list | grep rust-src` also shows that I have rust-src installed.

I tried to specify `rust-src` manually through `export XARGO_RUST_SRC=/home/nzzt/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library`, and I succeeded in the next step, but unfortunately another error occurred.

I checked the directory on my computer and found that it didn't match the actual directory.

![image](https://user-images.githubusercontent.com/7029338/89765652-dc66aa00-db4a-11ea-9732-797ea99eef31.png)

![image](https://user-images.githubusercontent.com/7029338/89779299-1e034f00-db63-11ea-8499-cd7a0a1145cd.png)

**Comment by ascjones** [comment]
It does look like `nightly` is your default toolchain, but anyway double check that it is installed with `rustup component list --toolchain nightly | grep rust-src`. If it's not you can do `rustup component add rust-src --toolchain nightly`

**Comment by aniiantt** [comment]
➜  flipper rustup component list --toolchain nightly | grep rust-src
rust-src (installed)

=========================
I compared the code with someone else who could build normally, and I found an interesting problem. His rust-src directory is `.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src`, but my rust-src directory is `.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library`. 

![image](https://user-images.githubusercontent.com/7029338/89879758-80b62280-dc17-11ea-9c2a-4b45427fee08.png)

This looks like a version upgrade issue. I'm not very familiar with Rust, I'm not sure.

**Comment by ascjones** [comment]
Yeah mine is also `rust/src`, which is what I would expect it to be. Could try reinstalling everything, or perhaps do `rustup update --toolchain nightly && rustup component add rust-src --toolchain nightly`

**Comment by aniiantt** [comment]
@ascjones 
In fact, not only have I reinstalled it,  I've also tried it on a newly installed server. I've tried it on three computers. I get the same error.

**Comment by aniiantt** [comment]
![image](https://user-images.githubusercontent.com/7029338/89891119-a13aa880-dc28-11ea-86b9-428835b74592.png)
![image](https://user-images.githubusercontent.com/7029338/89891145-a8fa4d00-dc28-11ea-884c-f3e15a0de6ee.png)
Perhaps it is because of a recent change in the structure of rust's source code.

**Comment by aniiantt** [comment]
After I installed the old version nightly, The problem was solved. When installing rust-src, It also need to specify the version. like `rustup component add rust-src --toolchain nightly-2020-07-11`

**Comment by ascjones** [comment]
Ah yes: https://github.com/rust-osdev/cargo-xbuild/issues/88

**Comment by ascjones** [comment]
See #71, I won't merge this yet but you can install from the PR branch if you want to use it in the meantime.

**Comment by MaciejBaj** [comment]
@aniiantt Bumping `cargo-xbuild` to `0.6.0` works

**Comment by Valentine-Mario** [comment]
Upgrading cargo-xbuild didn't seem to work for me.
