### ISSUE TITLE
Can't build flipper with cargo-contract 0.6.1

### ISSUE THREAD

**Issue by yangwao** [paritytech/cargo-contract#74]
Hello, I've had a similar problem like https://github.com/paritytech/cargo-contract/issues/70 and I think instruction on https://substrate.dev/substrate-contracts-workshop/#/0/setup are fairly broken now.

I think problem is that `cargo install cargo-contract --vers 0.6.1 --force` doesn't update to recent `cargo-xbuild-0.6.0` and that's where it gets stuck. On 0.7.0 there are I think different problems.

After I've bumped `cargo-xbuild` to version 0.6.0. I'm doing it right?

![image](https://user-images.githubusercontent.com/5887929/90313507-70e75880-df0d-11ea-8e85-10ffb585a03f.png)

```
❯ rustup show
Default host: x86_64-apple-darwin
rustup home:  /Users/wao/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-2019-11-06-x86_64-apple-darwin
nightly-2020-07-11-x86_64-apple-darwin
nightly-x86_64-apple-darwin

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.45.2 (d3fb005a3 2020-07-31)
```

**Comment by ascjones** [comment]
Yeah `0.7.0` is only compatible with `ink! 3.0` which is not yet released.

I will have to do an intermediate release with the new version of `cargo-xbuild`. It's compiled in as a library so it won't use the installed binary on your system.

**Comment by ascjones** [comment]
Just released `0.6.2` with the updated `cargo-xbuild`, can you install it and confirm it fixes the issue for you?

**Comment by yangwao** [comment]
@ascjones looks like we are flying ✅ Thank you! 💯 
![image](https://user-images.githubusercontent.com/5887929/90397156-b8015500-e097-11ea-8eba-a8c0cd07de1b.png)

**Comment by Valentine-Mario** [comment]
I'm still having the same problem with cargo-xbuild 0.6.0 and cargo contract 0.6.2
