### ISSUE TITLE
Error when building contract - error[E0158]: associated consts cannot be referenced in patterns

### ISSUE THREAD

**Issue by CrommVardek** [paritytech/cargo-contract#745]
Hello, 

From the flipper example, when executing `cargo +nightly contract build` the following error is thrown : 

`error[E0158]: associated consts cannot be referenced in patterns`  
```
    |
9  | /     pub struct Flipper {
10 | |         value: bool,
11 | |     }
   | |_____^
```

`cargo --version` returns `cargo 1.63.0 (fd9c4297c 2022-07-01)`
`cargo +nightly -V` returns `cargo 1.65.0-nightly (082503982 2022-09-13)`
` rustc --version` returns `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
and `cargo contract -V` return `cargo-contract 1.5.0-unknown-x86_64-unknown-linux-gnu`

the issue have been reported multiple times on Substrate.StackExchange ([here](https://substrate.stackexchange.com/questions/4785/errore0158-when-testing-default-contract-from-flipper/4847#4847), [here](https://substrate.stackexchange.com/questions/4806/ink-error-while-running-the-flipper-contract-with-no-modifications) and [here](https://substrate.stackexchange.com/questions/4810/contract-flipper-build-fails) )

Although a workaround have been explained [https://substrate.stackexchange.com/a/4847/151](https://substrate.stackexchange.com/a/4847/151), to me it's still a bug, and I don't understand why it does not work as it's supposed to?

**Comment by kayabaNerve** [comment]
This only stopped working in a recent Rust nightly. I'm not sure if Rust nightly tightened, or if Rust nightly had a regression. Regardless, I hope to see this resolved.

**Comment by abhijeetbhagat** [comment]
faced the same error today. workaround linked did the trick, although, i had to download the latest binaryen and replace system package mgr installed version.

**Comment by xgreenx** [comment]
It is problem with the generated code in the ink! https://github.com/paritytech/ink/issues/1417
