### ISSUE TITLE
Unable to build ink `4.0.0-alpha.3` using cargo-contract `2.0.0-alpha.3`

### ISSUE THREAD

**Issue by boyswan** [paritytech/cargo-contract#757]
I'm coming across `ERROR: Mismatching versions of parity-scale-codec were found!` when trying to build ink using cargo-contract. I'm aware of [this issue](https://github.com/paritytech/cargo-contract/issues/746), however I have both installed and run cargo-contract on stable.

```
❯ rustup default
stable-x86_64-apple-darwin (default)

❯ cargo contract -V
cargo-contract 2.0.0-alpha.3-unknown-x86_64-apple-darwin
```
```
[dependencies]
ink = "4.0.0-alpha.3"
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }
...
```

If I downgrade cargo-contract to 2.0.0-alpha.2, then I get `ERROR: No 'ink_lang' dependency found.` I've also tried using master from the ink repo, but keep running into one of these two errors.

**Comment by athei** [comment]
Works for me.

Please post your complete manifest cause this
```
ink = "4.0.0-alpha.3"
```
is wrong. You need `default-features = false`. Have a look at what `cargo contract new` outputs.

**Comment by boyswan** [comment]
Unfortunately running into the same issue even with  `default-features = false`.

The same error happens when building a fresh project via `cargo contract new` and running `cargo contract build`

**Comment by boyswan** [comment]
After running `cargo contract test` the issue was revealed!
`ERROR: The minimum Rust version is 1.63.0. You are using 1.61.0.`

Updating Rust solved the problem
