### ISSUE TITLE
Why pass a `-z`  flag to linker when build contract?

### ISSUE THREAD

**Issue by vita-dounai** [paritytech/cargo-contract#76]
https://github.com/paritytech/cargo-contract/blob/cfc389db2370be7661d5d2b17596ca7b71bca2bc/src/cmd/build.rs#L59-L62

**Comment by cmichi** [comment]
@vita-dounai The `-z` is to specify the stack size, the following command is synonymous to the one you posted (and we actually changed to this version just recently):
```
"-C link-arg=-zstack-size=65536 -C link-arg=--import-memory",
```
