### ISSUE TITLE
Unnecessary requirements when uploading a contract

### ISSUE THREAD

**Issue by deuszx** [paritytech/cargo-contract#892]
Currently, `cargo contract upload` requires `Cargo.toml` and, by extensions, all of the contract's dependencies. This means that in practice I can't simply give someone my `*.wasm` or `*.contract` files for upload.

If I understand the code correctly, it uses that information to construct a [`transcoder`](https://github.com/paritytech/cargo-contract/blob/master/crates/cargo-contract/src/cmd/extrinsics/upload.rs#L80) which is then [passed into](https://github.com/paritytech/cargo-contract/blob/master/crates/cargo-contract/src/cmd/extrinsics/upload.rs#L126) [`upload_code`](https://github.com/paritytech/cargo-contract/blob/master/crates/cargo-contract/src/cmd/extrinsics/upload.rs#L176) for [decoding events](https://github.com/paritytech/cargo-contract/blob/master/crates/cargo-contract/src/cmd/extrinsics/upload.rs#L189) upon uploading. 

Is it really required? Are there any contract-specific events that can be returned during contract upload? Or is the current state an unfortunate result of reusing code (`DisplayEvents`) that seemed similar enough?

For example, both the official wallet and ContractsUI work fine with just the `*.wasm` or `*.contract` files.

**Comment by ascjones** [comment]
You are absolutely right, we should provide the ability to work with just `wasm` or `contract` files. As you say though, when uploading a plain `wasm` file it won't be able to decode the events, but we can get around that by allowing it and just not showing the decoded events.

**Comment by deuszx** [comment]
Hey @ascjones , thanks for quick reply 👋 

Not decoding events would be quite a downside but I'm wondering whether it's _really_ necessary here -- when uploading. Aren't the only events emitted then coming from other pallets, like `Balance` or `System`? I.e. there's no need to include contract's metadata b/c there will be no contract-specific events to decode.

**Comment by ascjones** [comment]
Yes you are right, contract metadata is not required at all for `upload`.

**Comment by ascjones** [comment]
I've been wanting to do this for a while, and unify across the extrinsics, so have made a start on it in #893.

**Comment by deuszx** [comment]
Similarly, `cargo contract call` should require only the metadata file.

**Comment by ascjones** [comment]
Agreed, I plan to do that as part of #893.
