### ISSUE TITLE
error: the argument '[FILE]' cannot be used with '--manifest-path <MANIFEST_PATH>'

### ISSUE THREAD

**Issue by forgetso** [paritytech/cargo-contract#908]
The v2 release candidate seems to fail when passing `manifest-path`. This command worked with versions < 2.
```
cargo contract instantiate "/contracts/target/ink/dapp.wasm" --args 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY 1000000000000 --constructor "default" --suri "//Alice" --value 2000000000000 --url "ws://localhost:9944" --manifest-path "./contracts/Cargo.toml"
```

```
cargo contract --version
cargo-contract-contract 2.0.0-rc-3c084d2-x86_64-unknown-linux-gnu
```

**Comment by forgetso** [comment]
Turns out this happens when you're already in the `contracts` folder and that folder contains the `Cargo.toml`, therefore, specifiying `manifest-path` doesn't make sense.

**Comment by ascjones** [comment]
This is expected behaviour now since https://github.com/paritytech/cargo-contract/pull/893. 

You can *either* supply the path to the artifact directly, *or* the `--manifest-path`, but not both. The manifest path is just used to locate the artifact.

**Comment by forgetso** [comment]
Thanks
