### ISSUE TITLE
undefined reference to `__ink_generate_metadata'

### ISSUE THREAD

**Issue by forgetso** [paritytech/cargo-contract#909]
Hi,

I'm unable to generate the metadata when compiling a contract that has a reference to a second contract using `cargo-contract-contract 2.0.0-rc-3c084d2-x86_64-unknown-linux-gnu`.

```
error: linking with `cc` failed: exit status: 1

...

  = note: /usr/bin/ld: /home/user/dev/prosopo/dapp-example/contracts/target/ink/release/deps/metadata_gen-fb8a1845a23ecd3e.metadata_gen.4b911e9c-cgu.12.rcgu.o: in function `metadata_gen::main':
          metadata_gen.4b911e9c-cgu.12:(.text._ZN12metadata_gen4main17hecbff74e26d81eb9E+0x11): undefined reference to `__ink_generate_metadata'

          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `metadata-gen` due to previous error
ERROR: `"/home/user/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo" "run" "--package" "metadata-gen" "--manifest-path=/tmp/cargo-contract_dsvUuc/Cargo.toml" "--target-dir=/home/user/dev/prosopo/dapp-example/contracts/target/ink" "--release" ""` failed with exit code: Some(101)


```

The contract tomls are [here](https://github.com/prosopo/protocol/blob/inkv4/contracts/Cargo.toml) and [here](https://github.com/prosopo/dapp-example/blob/inkv4/contracts/Cargo.toml). The second one references the first one in its toml. The first contract compiles ok.

```
rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/user/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2022-03-14-x86_64-unknown-linux-gnu
nightly-2022-06-20-x86_64-unknown-linux-gnu
nightly-2022-06-30-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.68.0-nightly (4781233a7 2023-01-16)

```

I've now tried this with both a local copy of cargo-contract and when installed using `cargo install cargo-contract --version 2.0.0-rc`.

**Comment by forgetso** [comment]
It seems like linking this function is not working.

```
extern "Rust" {
    // Note: The ink! metadata codegen generates an implementation for this function,
    // which is what we end up linking to here.

    fn __ink_generate_metadata() -> ink::metadata::InkProject;
}
```

**Comment by forgetso** [comment]
Seems related to https://github.com/paritytech/cargo-contract/pull/199#issue-815219048

**Comment by HCastano** [comment]
@forgetso we recently merged some changes around contracts depending on other contracts. See https://github.com/paritytech/cargo-contract/issues/927.

Can you try again with the latest ink! and `cargo-contract` releases?

**Comment by forgetso** [comment]
Hi @HCastano, I've now tried with the following versions and I'm hitting the same error:

In both parent and child contract, using [`v4.0.0-rc`](https://github.com/paritytech/ink/commit/50b32f4e49d4072f3d28009eb517475b68bec56b)
```
ink = { git = "https://github.com/paritytech/ink", rev="59bbd36c1161370697882532c21ee1833e729f13", default-features = false }
```

With
```
cargo contract --version
cargo-contract-contract 2.0.0-rc.1-0a98d16-x86_64-unknown-linux-gnu
```

Returns

```
          metadata_gen.a505040f-cgu.13:(.text._ZN12metadata_gen4main17hef77d893018b6d58E+0x11): undefined reference to `__ink_generate_metadata'
          collect2: error: ld returned 1 exit status
          
  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `metadata-gen` due to previous error
ERROR: `"/home/chris/.rustup/toolchains/1.67.0-x86_64-unknown-linux-gnu/bin/cargo" "run" "--package" "metadata-gen" "--manifest-path=/tmp/cargo-contract_9u8kw6/Cargo.toml" "--target-dir=/home/chris/dev/prosopo/dapp-example/contracts/target/ink" "--release" "" "--verbose"` failed with exit code: Some(101)

```

**Comment by forgetso** [comment]
Correction, I was using this commit for ink: https://github.com/paritytech/ink/commit/50b32f4e49d4072f3d28009eb517475b68bec56b

**Comment by HCastano** [comment]
@forgetso I managed to reproduce this, but I still need to dig in further to see what's wrong.

Can you do a few things in the meantime:
- Update to ink! 4.0
  - This will involve cleaning up a few things from your `Cargo.toml` file, see the template from `cargo-contract`
- Make sure the branch references are still up to date, there are some dead links in your descriptions and `Cargo.toml`'s (e.g no more `inkv4` branch in the `protocol` repo)
- Create a minimal reproducer, ideally in a single repo (this would be the most helpful thing)

**Comment by forgetso** [comment]
Apologies, the `inkv4` branch is merged into `develop` and we auto purge old branches. I'll create a reproducible example and upgrade ink.

**Comment by forgetso** [comment]
Here is a reproducible example using `inkv4` with  instructions.

https://github.com/prosopo/ink_generate_metadata

**Comment by HCastano** [comment]
> It looks like the cargo contract templates [are still using the ink release candidate](https://github.com/paritytech/cargo-contract/blob/9502d89de7e975a0c942b738ee9a177f54eba101/crates/build/templates/new/_Cargo.toml) btw.

Haha, yeah I noticed yesterday https://github.com/paritytech/cargo-contract/pull/971 😅

**Comment by ascjones** [comment]
Should be fixed with https://github.com/paritytech/cargo-contract/pull/977.

For an immediate fix try adding `default = ["std"]` to the `[features]` section of your `Cargo.toml`

**Comment by forgetso** [comment]
Thanks guys, very much appreciated!
