### ISSUE TITLE
Fail the build if wasm-opt not installed

### ISSUE THREAD

**Issue by ascjones** [paritytech/cargo-contract#91]
Currently a warning is displayed if `wasm-opt` is not installed. However some users are not reading the warning.

https://github.com/paritytech/cargo-contract/blob/d28a743b32a77d2ab3ddb463d101e1fe91344b15/src/cmd/build.rs#L201-L208

Since contract authors would definitely want their contracts optimized (storage rent!), we should fail the build if it is not installed. They won't be able to ignore that.

If for whatever reason they want to still compile without installing `wasm-opt`, we should provide an option e.g. `--no-wasm-opt` or `--skip-wasm-optimizations`

## Alternative

Investigate using https://github.com/pepyakin/binaryen-rs as a dependency so as not to require manual installation of `wasm-opt`

**Comment by Robbepop** [comment]
I heavily lean towards the longer, more disgusting `--skip-wasm-optimizations` since we really don't want to bring any additional comfort to this decision.
