### ISSUE TITLE
cargo contract does too much work on unchanged contracts

### ISSUE THREAD

**Issue by athei** [paritytech/cargo-contract#949]
Follow up of #926.

The following behaviour still slows down builds of unchanged contracts. This is important because of the e2e-tests which re-compile dependency contracts which are usually unchanged ( https://github.com/paritytech/ink/issues/1622 ):

- postprocessing of wasm file
- recompiling of metadata-gen v0.1.0

**Comment by ascjones** [comment]
@athei see #964 for a solution
