### ISSUE TITLE
Option to disable panic_immediate_abort

### ISSUE THREAD

**Issue by kvinwang** [paritytech/cargo-contract#953]
`cargo-contract` always add `-Zbuild-std-features=panic_immediate_abort` when building with `--release`.  This causes the panic message never be shown in the `debug_message` (#[panic_handler] never been called). 

It would be helpful to add an option the disable the `panic_immediate_abort`. 

Or can we just remove the `-Zbuild-std-features=panic_immediate_abort`?  Because ink already has a feature gate `ink-debug` to switch the `panic_handler` between `printing a message` and `doing nothing`.

**Comment by ascjones** [comment]
It's to do with making `--release` contracts as small as possible. The panic machinery and messages use a lot of code.

> Or can we just remove the -Zbuild-std-features=panic_immediate_abort? Because ink already has a feature gate ink-debug to switch the panic_handler between printing a message and doing nothing.

Perhaps we could add an option which allow you to disable this for release builds if you don't mind the bigger contract size and paying for it.

**Comment by athei** [comment]
Please note that the "debug" build still uses all optimizations. It just leaves the panic messages in. With this information, do you still think this feature is useful?

> Or can we just remove the `-Zbuild-std-features=panic_immediate_abort`? Because ink already has a feature gate `ink-debug` to switch the `panic_handler` between `printing a message` and `doing nothing`.

This would be the worst of both worlds. The core lib will pull in all the string formatting code and then throw away the massage inside the panic handler.

**Comment by kvinwang** [comment]
> Please note that the "debug" build still uses all optimizations. It just leaves the panic messages in. With this information, do you still think this feature is useful?

Ah, you mean `cargo-contract` always builds the program with `cargo build --release ...`. Didn't know that. If so, there is no need to add an option to disable the panic_immediate_abort.
