### ISSUE TITLE
Error installing cargo-dylint

### ISSUE THREAD

**Issue by manangouhari** [paritytech/cargo-contract#957]
I'm attempting to install `cargo-dylint` which is a dependency for `cargo-contracts` on an M1 MacBook Pro. 

I'm running into an error that is related to `openssl`. See below:
![image](https://user-images.githubusercontent.com/31039184/217081519-c27a2177-5686-48c8-8b1a-cec6bb749b2c.png)

I've installed `openssl@3` using: `brew install openssl@3` and tried a a bunch of things.

Can't seem to figure this out. Any help would be appreciated, thanks!

**Comment by manangouhari** [comment]
This is complete [output log](https://gist.github.com/manangouhari/9fa4fcea7f0e7af172eae8e357dfd0c7) from running `cargo install cargo-dylint`.

**Comment by SkymanOne** [comment]
since the latest release, `cargo-dyling` is not required for installation, we simply don't have any lints yet

**Comment by manangouhari** [comment]
Thanks! Updating to the latest version helped.
