### ISSUE TITLE
Default to dry-run's for sub-commands + Add `--exec`

### ISSUE THREAD

**Issue by cmichi** [paritytech/cargo-contract#979]
The usage of the call command together with the `--skip-dry-run` and `--dry-run` flags has posed to be not ideal for users. 

We had discussed this and came up with the following ideas to improve the usability.

### Default to dry-run's by default

This should be done in all commands: `instantiate`, `call`, etc.
Explicitly write to stdout that "no state changes were performed".

### Add a new flag `--exec` (or similar) to `call`, `instantiate`, etc.

Using this flag will issue the transaction on-chain.

### Add a new sub-command `cargo contract exec`

It will be a shortcut for `cargo contract call --exec`.

**Comment by HCastano** [comment]
If we go with flags, I'd do `--execute/-x` as this is what other tools in the Rust ecosystem already use (e.g `cargo-release`).

If we want to rename commands I'd do something like `query` for dry-runs and keep `call` as is.
